import React, { useState } from 'react';
import { CalendarHeart, Clock3, Heart, Sparkles } from 'lucide-react';

const moments = [
  { label: 'Until the next call', value: 'Soon', copy: 'The clock is not measuring distance. It is measuring how long until Abu hears Samjhana’s voice again.' },
  { label: 'Until the next birthday', value: 'A new chapter', copy: 'Another year of Samjhana being exactly herself, and Abu finding new reasons to celebrate her.' },
  { label: 'Until the next visit', value: 'Worth the wait', copy: 'A future day when a screen is no longer needed and the first hello can happen in the same room.' },
  { label: 'Until the ordinary life', value: 'Still coming', copy: 'The most important countdown has no fixed number: it ends when the light-blue scooter, the road, and both of us arrive together.' },
];

export default function AnniversaryCountdownClockPage() { const [selected, setSelected] = useState(0); const moment = moments[selected]; return <main className="min-h-dvh bg-[#e8e4f2] px-5 py-12 text-[#302c48] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-violet-900/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-violet-700"><CalendarHeart className="h-4 w-4" /> Abu’s waiting-room clock</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">The best countdown ends with you here.</h1></div><p className="max-w-xs text-sm leading-7 text-[#685e83]">Four things Abu is willing to wait for, because not every important moment can be scheduled.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Choose a waiting-room moment">{moments.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-violet-700 bg-white shadow-xl' : 'border-violet-900/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-violet-700">Moment 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.label}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#302c48] p-8 text-[#f8f4ff] shadow-2xl sm:p-14"><div className="absolute right-10 top-10 grid h-24 w-24 place-items-center rounded-full border border-violet-200/25"><Clock3 className="h-9 w-9 text-violet-200" /></div><Sparkles className="h-10 w-10 text-violet-200" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-violet-200">{moment.label}</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{moment.value}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-white/70">{moment.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-white/15 pt-6 text-sm font-black text-violet-100"><Heart className="h-4 w-4 fill-current text-rose-300" /> Abu is counting with hope, not pressure.</div></section></div></div></main>; }
