import React, { useState } from 'react';
import { Flame, Heart, Sparkles } from 'lucide-react';

const wishes = [
  { label: 'The wish for today', copy: 'May Samjhana feel celebrated in every room she enters, especially the quiet ones where she forgets how much light she carries.' },
  { label: 'The wish for our distance', copy: 'May every Nepalgunj–Sakai call arrive at the right moment and leave both of us a little less lonely.' },
  { label: 'The wish for the future', copy: 'May the roads to Bardiya, Pokhara, Manang, and Mustang eventually become memories we can point to together.' },
];
export default function CandleBlowerPage() { const [selected, setSelected] = useState(0); const wish = wishes[selected]; return <main className="min-h-dvh bg-[#17131b] px-5 py-12 text-[#fff7e8] sm:px-10 sm:py-16"><div className="mx-auto max-w-6xl"><header className="border-b border-amber-100/15 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-amber-200"><Flame className="h-4 w-4" /> The birthday candle room</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">I am keeping three wishes lit for you.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-white/60">Choose a wish. The flame is only a symbol; the promise underneath is real.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><nav className="space-y-3" aria-label="Birthday wishes">{wishes.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-amber-200/70 bg-white/10 shadow-xl' : 'border-white/10 bg-white/5 hover:bg-white/10'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-amber-200">Wish 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.label}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-rose-950 via-[#5b2438] to-amber-900 p-8 shadow-2xl sm:p-14"><div className="absolute left-1/2 top-12 h-32 w-32 -translate-x-1/2 rounded-full bg-amber-200/15 blur-3xl" /><Sparkles className="relative h-10 w-10 text-amber-200" /><p className="relative mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-amber-200">{wish.label} · Abu’s birthday note</p><h2 className="relative mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{wish.copy}</h2><div className="relative mt-10 flex items-center gap-3 border-t border-white/15 pt-6 text-sm font-bold text-amber-100/75"><Heart className="h-4 w-4 fill-current text-rose-300" /> For my Bhuntu, with the light left on.</div></section></div></div></main>; }
