import React, { useState } from 'react';
import { CalendarDays, Flag, MapPinned } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function CoupleMilestoneMap2Page() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [selected, setSelected] = useState(0); const photo = getAssetUrl(ALL_MEDIA_PHOTOS[66 % ALL_MEDIA_PHOTOS.length]); const moments = [['28 Oct 2025', 'The day Samjhana said yes to Abu.'], ['Dhamboji', 'The city where our story learned its first streets.'], ['Sakai, Osaka', 'The distance that taught us how to stay close.']];
  return <main className="min-h-[76dvh] bg-[#f3f0e8] px-5 py-12 text-[#2c3028] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[#a26a37]"><MapPinned className="h-7 w-7" /><span className="text-xs font-black uppercase tracking-[.3em]">A map with no borrowed milestones</span></div><h1 className="mt-5 max-w-4xl text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><div className="mt-12 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><section className="relative overflow-hidden rounded-[2rem] bg-[#ded6c2] p-5"><img src={photo} alt="A relationship milestone memory" className="h-72 w-full rounded-[1.5rem] object-cover opacity-80" loading="lazy" /><div className="mt-6 space-y-3">{moments.map(([date, text], i) => <button type="button" key={date} onClick={() => setSelected(i)} className={selected === i ? 'flex w-full items-center gap-4 rounded-2xl bg-[#2c3028] p-4 text-left text-[#f7f1df]' : 'flex w-full items-center gap-4 rounded-2xl bg-white/60 p-4 text-left'}><Flag className="h-5 w-5 shrink-0 text-[#a26a37]" /><span><span className="block text-xs font-black uppercase tracking-[.15em] opacity-60">{date}</span><span className="mt-1 block font-bold">{text}</span></span></button>)}</div></section><aside className="rounded-[2rem] border border-[#d7ceb9] bg-white p-7 shadow-xl"><CalendarDays className="h-7 w-7 text-[#a26a37]" /><h2 className="mt-7 text-3xl font-black">{moments[selected][1]}</h2><p className="mt-5 leading-8 text-[#6f7568]">{gift.message}</p><p className="mt-6 border-t border-[#e8dfcf] pt-5 text-sm leading-7 text-[#6f7568]">{gift.gift} {gift.surprise}</p></aside></div></div></main>;
}
