import React, { useState } from 'react';
import { Heart, Orbit, Sparkles, Star } from 'lucide-react';

const stars = [
  { name: 'The Abu star', copy: 'Named for the nickname Samjhana gave Abhay, because one small word can become a whole constellation of meaning.' },
  { name: 'The Dhamboji star', copy: 'A bright point for the places where ordinary days began turning into memories Abu wanted to keep.' },
  { name: 'The call star', copy: 'A steady light between Nepalgunj and Sakai, proof that connection can be built one evening at a time.' },
  { name: 'The road star', copy: 'A future light for Bardiya, Pokhara, Manang, Mustang, and the journeys that are still waiting for both names.' },
];

export default function CoupleStarryPlanetariumPage() { const [selected, setSelected] = useState(0); const star = stars[selected]; return <main className="min-h-dvh bg-[#090d1f] px-5 py-12 text-white sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-white/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-sky-200"><Orbit className="h-4 w-4" /> Abu & Bhuntu observatory</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">The sky has room for every version of us.</h1></div><p className="max-w-xs text-sm leading-7 text-white/60">Four stars Abu would name if he could turn the memories into a private night sky.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Planetarium stars">{stars.map((item, index) => <button key={item.name} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-sky-200/70 bg-white/10 shadow-xl' : 'border-white/10 bg-white/5 hover:bg-white/10'}`}><span className="flex items-center gap-3"><Star className="h-5 w-5 fill-sky-200 text-sky-200" /><span className="text-lg font-black">{item.name}</span></span><span className="mt-3 block text-[10px] font-black uppercase tracking-[0.18em] text-white/45">Star 0{index + 1}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-950 via-slate-900 to-sky-950 p-8 shadow-2xl sm:p-14"><div className="absolute right-12 top-12 h-2 w-2 rounded-full bg-sky-200 shadow-[0_0_40px_18px_rgba(186,230,253,.8)]" /><Sparkles className="h-10 w-10 text-sky-200" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-sky-200">Star 0{selected + 1} · named by Abu</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{star.name}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-white/70">{star.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-white/15 pt-6 text-sm font-black text-sky-100"><Heart className="h-4 w-4 fill-current text-rose-300" /> Samjhana is Abu’s brightest coordinate.</div></section></div></div></main>; }
