import React, { useState } from 'react';
import { Film, Heart, Play, Ticket } from 'lucide-react';

const chapters = [
  { title: 'Opening scene · The yes', copy: '28 October 2025: the proposal was accepted, and the story finally got a title only the two of us could understand.' },
  { title: 'Middle act · The calls', copy: 'Nepalgunj and Sakai learned how to share a soundtrack: late-night video calls, small updates, and the comfort of being remembered.' },
  { title: 'Favourite scene · The food', copy: 'Chau-Chau, Panipuri, momo, and the way a simple craving could turn into an entire memory.' },
  { title: 'Post-credit scene · The road', copy: 'The light-blue scooter, Bardiya, Pokhara, Manang, Mustang—and the future Abu is still writing beside you.' },
];

export default function CoupleMovieMarathonPage() { const [selected, setSelected] = useState(0); const chapter = chapters[selected]; return <main className="min-h-dvh bg-[#17151d] px-5 py-12 text-[#f8f2e8] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-white/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-rose-200"><Film className="h-4 w-4" /> Abu & Bhuntu picture house</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">The film is called us.</h1></div><p className="max-w-xs text-sm leading-7 text-white/60">Four chapters, no generic plot, and one favourite lead character: Samjhana.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Cinema chapters">{chapters.map((item, index) => <button key={item.title} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-rose-200/70 bg-white/10 shadow-xl' : 'border-white/10 bg-white/5 hover:bg-white/10'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-rose-200">Chapter 0{index + 1}</span><span className="mt-3 block text-lg font-black">{item.title}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-rose-950 via-fuchsia-900 to-indigo-950 p-8 shadow-2xl sm:p-14"><div className="absolute right-10 top-10 h-24 w-16 rounded-t-full border border-rose-200/25" /><Ticket className="h-10 w-10 text-rose-200" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-rose-200">Now screening · chapter 0{selected + 1}</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{chapter.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-white/70">{chapter.copy}</p><button type="button" onClick={() => setSelected((selected + 1) % chapters.length)} className="mt-10 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-black text-slate-900 transition hover:-translate-y-1 active:scale-[.98]"><Play className="h-4 w-4 fill-current" /> Screen the next chapter</button><div className="mt-10 flex items-center gap-3 border-t border-white/15 pt-6 text-sm font-black text-rose-100"><Heart className="h-4 w-4 fill-current text-rose-300" /> Written, directed, and kept by Abu.</div></section></div></div></main>; }
