import React, { useState } from 'react';
import { Heart, MessageCircle, PenLine, Sparkles } from 'lucide-react';

const prompts = [
  { label: 'A prompt about home', prompt: 'What makes a place feel like home to you?', note: 'Abu wants to learn the small things that make Samjhana feel safe, not only the places on a map.' },
  { label: 'A prompt about joy', prompt: 'Which ordinary moment would you happily repeat?', note: 'The answer may be food, laughter, a call, or something that seems small until the right person remembers it.' },
  { label: 'A prompt about distance', prompt: 'What helps you feel close when the map is not kind?', note: 'Abu wants to keep learning the rituals that make Nepalgunj and Sakai feel less far apart.' },
  { label: 'A prompt about the future', prompt: 'Which road should we take first?', note: 'Bardiya, Pokhara, Manang, Mustang—or a road neither of us has named yet.' },
];

export default function CoupleQuestionsDeepPage() { const [selected, setSelected] = useState(0); const prompt = prompts[selected]; return <main className="min-h-dvh bg-[#f2ede5] px-5 py-12 text-[#302c29] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-[#795e4e]/20 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-[#9c6045]"><MessageCircle className="h-4 w-4" /> Abu’s conversation table</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Prompts worth answering slowly.</h1></div><p className="max-w-xs text-sm leading-7 text-[#755f52]">Not a test. Four doors into the kind of conversation Abu hopes to keep having with Samjhana.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Conversation prompts">{prompts.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-[#9c6045] bg-white shadow-xl' : 'border-[#795e4e]/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-[#9c6045]">Prompt 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.label}</span></button>)}</nav><section className="rounded-[2rem] bg-[#fffaf1] p-8 shadow-[15px_18px_0_rgba(48,44,41,.12)] sm:p-14"><PenLine className="h-9 w-9 text-[#9c6045]" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-[#9c6045]">{prompt.label}</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{prompt.prompt}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#755f52]">{prompt.note}</p><div className="mt-10 flex items-center gap-3 border-t border-[#795e4e]/15 pt-6 text-sm font-black text-[#9c6045]"><Heart className="h-4 w-4 fill-current text-rose-400" /><Sparkles className="h-4 w-4" /> Abu is listening.</div></section></div></div></main>; }
