import React, { useState } from 'react';
import { Coffee, Heart, Home, Mountain, Sparkles } from 'lucide-react';

const rooms = [
  { label: 'The entryway', title: 'A place where your shoes are always welcome.', copy: 'The future begins with arriving without needing to say goodbye again.', icon: Home, tone: 'bg-rose-50' },
  { label: 'The kitchen', title: 'A table made for Chau-Chau and long conversations.', copy: 'Nothing elaborate: just food, warm light, and the familiar comfort of making space for each other.', icon: Coffee, tone: 'bg-amber-50' },
  { label: 'The window', title: 'A view toward every road we still want.', copy: 'Bardiya, Pokhara, Manang, Mustang, and the light-blue scooter waiting outside.', icon: Mountain, tone: 'bg-sky-50' },
  { label: 'The quiet room', title: 'A room where the distance finally rests.', copy: 'A soft place for calls that become unnecessary because Abu is already beside you.', icon: Heart, tone: 'bg-emerald-50' },
];

export default function CoupleFutureHome3DPage() { const [selected, setSelected] = useState(0); const room = rooms[selected]; const Icon = room.icon; return <main className="min-h-dvh bg-[#e9eee9] px-5 py-12 text-[#28352c] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-emerald-900/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-emerald-700"><Home className="h-4 w-4" /> Abu’s future-home blueprint</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">A home is made of how we treat the ordinary.</h1></div><p className="max-w-xs text-sm leading-7 text-[#617264]">Four rooms, four promises, and a future that feels beautiful because it includes the small things.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Future home rooms">{rooms.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-emerald-700 bg-white shadow-xl' : 'border-emerald-900/10 bg-white/45 hover:bg-white/80'}`}><item.icon className="h-5 w-5 text-emerald-700" /><span className="mt-5 block text-xl font-black">{item.label}</span><span className="mt-2 block text-[10px] font-black uppercase tracking-[0.18em] text-[#617264]">Room 0{index + 1}</span></button>)}</nav><section className={`relative overflow-hidden rounded-[2rem] ${room.tone} p-8 shadow-[15px_18px_0_rgba(40,53,44,.12)] sm:p-14`}><div className="absolute right-10 top-10 h-24 w-24 rounded-full border border-emerald-700/15" /><Icon className="h-10 w-10 text-emerald-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">{room.label} · blueprint note</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{room.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#617264]">{room.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-emerald-900/15 pt-6 text-sm font-black text-emerald-700"><Sparkles className="h-4 w-4" /> Designed for Abu and his Bhuntu.</div></section></div></div></main>; }
