import React, { useState } from 'react';
import { ArrowRight, CalendarHeart, Heart, Milestone } from 'lucide-react';

const moments = [
  { label: 'The yes', title: 'A door opened.', copy: '28 October 2025: the proposal became a yes, and Abu’s ordinary calendar began making room for Samjhana.' },
  { label: 'The becoming', title: 'A name became ours.', copy: 'Abhay became Abu, and every nickname from Samjhana started carrying its own kind of warmth.' },
  { label: 'The crossing', title: 'The distance learned our rhythm.', copy: 'Nepalgunj and Sakai became two ends of a call that kept choosing connection.' },
  { label: 'The continuing', title: 'The story kept moving.', copy: 'The next milestones are not only dates. They are roads, food memories, birthdays, and a future still being written.' },
];
export default function CoupleAnniversaryTimelinePage() { const [selected, setSelected] = useState(0); const moment = moments[selected]; return <main className="min-h-dvh bg-[#e8edf2] px-5 py-12 text-[#263743] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-slate-700/15 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-sky-700"><CalendarHeart className="h-4 w-4" /> Abu’s turning-point ledger</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">A timeline of the moments that changed the feeling.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#627783]">Four turning points, each more personal than a date on a calendar.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Relationship turning points">{moments.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`flex w-full items-center gap-4 rounded-2xl border p-5 text-left transition ${selected === index ? 'border-sky-700 bg-white shadow-xl' : 'border-slate-700/10 bg-white/45 hover:bg-white/80'}`}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-sky-100 text-xs font-black text-sky-700">0{index + 1}</span><span className="text-xl font-black">{item.label}</span></button>)}</nav><section className="rounded-[2rem] bg-[#f9fcff] p-8 shadow-[15px_18px_0_rgba(38,55,67,.12)] sm:p-14"><Milestone className="h-9 w-9 text-sky-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-sky-700">Turning point 0{selected + 1}</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{moment.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#627783]">{moment.copy}</p><button type="button" onClick={() => setSelected((selected + 1) % moments.length)} className="mt-10 inline-flex items-center gap-2 rounded-full bg-sky-700 px-5 py-3 text-sm font-black text-white transition hover:-translate-y-1 active:scale-[.98]">Follow the next moment <ArrowRight className="h-4 w-4" /></button><div className="mt-10 flex items-center gap-3 border-t border-slate-700/15 pt-6 text-sm font-black text-sky-700"><Heart className="h-4 w-4 fill-current text-rose-400" /> Abu keeps moving toward you.</div></section></div></div></main>; }
