import React, { useState } from 'react';
import { Compass, Flag, Send } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function CoupleBucketList2Page() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [place, setPlace] = useState(0); const photos = [59, 115, 169].map((i) => getAssetUrl(ALL_MEDIA_PHOTOS[i % ALL_MEDIA_PHOTOS.length])); const places = [['Bardiya', 'the first road Abu wants to take with you on the light-blue scooter'], ['Pokhara', 'a lakeside morning where nobody has to hang up'], ['Manang + Mustang', 'the mountain chapter we keep saving for our future']];
  return <main className="min-h-[76dvh] bg-[#edf4f5] px-5 py-12 text-[#20343b] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[#157b83]"><Compass className="h-7 w-7" /><span className="text-xs font-black uppercase tracking-[.3em]">Postcards Abu is saving</span></div><h1 className="mt-5 text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5f777d]">Not a random date generator. These are places from the future Abu actually imagines with Samjhana.</p><div className="mt-12 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-[2rem] bg-white p-5 shadow-xl"><div className="grid grid-cols-3 gap-3">{photos.map((photo) => <img key={photo} src={photo} alt="A future travel memory" className="h-52 w-full rounded-2xl object-cover" loading="lazy" />)}</div><div className="mt-7 grid gap-2">{places.map(([name], i) => <button type="button" key={name} onClick={() => setPlace(i)} className={place === i ? 'flex items-center gap-3 rounded-2xl bg-[#157b83] p-4 text-left text-white' : 'flex items-center gap-3 rounded-2xl border border-[#cde1e3] p-4 text-left text-[#157b83]'}><Flag className="h-5 w-5" /><span className="font-black">{name}</span></button>)}</div></section><aside className="rounded-[2rem] border border-[#cde1e3] bg-[#dff1f1] p-7"><Send className="h-7 w-7 text-[#157b83]" /><p className="mt-7 text-xs font-black uppercase tracking-[.2em] text-[#157b83]/70">Postcard {place + 1} of 3</p><h2 className="mt-4 text-3xl font-black">{places[place][0]}</h2><p className="mt-4 text-lg leading-8 text-[#47646b]">{places[place][1]}.</p><p className="mt-7 border-t border-[#bfdfe1] pt-5 text-sm leading-7 text-[#47646b]">{gift.message} {gift.gift} {gift.surprise}</p></aside></div></div></main>;
}
