import React, { useState } from 'react';
import { Clapperboard, Heart, Popcorn, Ticket } from 'lucide-react';

const moments = [
  { label: 'Before the film', title: 'Choose the snack first.', copy: 'Chau-Chau, Panipuri, or the snack neither of us planned but both of us end up sharing.' },
  { label: 'During the film', title: 'Pause for the little commentary.', copy: 'The best part is not always the plot. It is hearing what Samjhana notices, laughs at, or wants to explain to Abu.' },
  { label: 'After the film', title: 'Stay for the quiet credits.', copy: 'A comfortable silence, a last message, and the feeling that a normal evening can still become a memory worth keeping.' },
];

export default function CoupleMovieNightPage() { const [selected, setSelected] = useState(0); const moment = moments[selected]; return <main className="min-h-dvh bg-[#191722] px-5 py-12 text-[#fff8ef] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-white/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-amber-200"><Clapperboard className="h-4 w-4" /> Abu & Bhuntu’s one-evening cinema</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">The plot is simple: stay a little longer.</h1></div><p className="max-w-xs text-sm leading-7 text-white/60">A three-part itinerary for a movie night where the real story is the person beside the screen.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Movie night itinerary">{moments.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-amber-200/70 bg-white/10 shadow-xl' : 'border-white/10 bg-white/5 hover:bg-white/10'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-amber-200">Scene 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.label}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-rose-950 via-fuchsia-950 to-indigo-950 p-8 shadow-2xl sm:p-14"><div className="absolute right-10 top-10"><Popcorn className="h-12 w-12 rotate-12 text-amber-200/60" /></div><Ticket className="h-10 w-10 text-amber-200" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-amber-200">{moment.label} · private screening</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{moment.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-white/70">{moment.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-white/15 pt-6 text-sm font-black text-amber-100"><Heart className="h-4 w-4 fill-current text-rose-300" /> Reserved for Samjhana · hosted by Abu.</div></section></div></div></main>; }
