import React, { useState } from 'react';
import { Heart, Key, Sparkles } from 'lucide-react';

const names = [
  { name: 'Sanzu', reason: 'The bright name', copy: 'The name that arrives with a little light in it, like Samjhana is already smiling before Abu sees her.' },
  { name: 'Bhuntu', reason: 'The home name', copy: 'The name that became a birthday website, a password, and a whole trail made carefully by Abu.' },
  { name: 'Bhoot', reason: 'The playful name', copy: 'For the mischievous, funny, impossible-to-ignore version of Samjhana that Abu secretly loves most.' },
  { name: 'Runchi', reason: 'The soft name', copy: 'A tender name for the moments when affection does not need to be loud to be completely real.' },
];
export default function CoupleNicknameGeneratorPage() { const [selected, setSelected] = useState(0); const name = names[selected]; return <main className="min-h-dvh bg-[#eee6f4] px-5 py-12 text-[#352a45] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-violet-900/15 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-violet-700"><Key className="h-4 w-4" /> Abu’s name atelier</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Every name you gave me became a different kind of love.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#6d6082]">No generator needed. These are the real names Abu keeps, with the reasons each one feels like Samjhana.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Samjhana’s names">{names.map((item, index) => <button key={item.name} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-violet-700 bg-white shadow-xl' : 'border-violet-900/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-violet-700">Name 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.name}</span></button>)}</nav><section className="rounded-[2rem] bg-[#fffaff] p-8 shadow-[15px_18px_0_rgba(53,42,69,.12)] sm:p-14"><Sparkles className="h-9 w-9 text-violet-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-violet-700">{name.reason}</p><h2 className="mt-5 text-7xl font-black tracking-[-0.08em] sm:text-9xl">{name.name}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#6d6082]">{name.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-violet-900/15 pt-6 text-sm font-black text-violet-700"><Heart className="h-4 w-4 fill-current text-rose-400" /> Kept by Abu for his Bhuntu.</div></section></div></div></main>; }
