import React, { useState } from 'react';
import { Hand, Heart, LockKeyhole, Sparkles } from 'lucide-react';

const gestures = [
  { label: 'Gesture one', title: 'Say the nickname softly.', copy: 'A secret handshake can begin with a name: Sanzu, Bhuntu, Bebo, Sanu, or Runchi, depending on the feeling of the day.' },
  { label: 'Gesture two', title: 'Remember the small detail.', copy: 'Chau-Chau, Panipuri, a place, a message, or a passing thought becomes meaningful when Abu carries it forward.' },
  { label: 'Gesture three', title: 'Make the call anyway.', copy: 'Distance does not need a perfect evening. It only needs two people willing to keep showing up between Nepalgunj and Sakai.' },
  { label: 'Gesture four', title: 'Leave a hand free for the future.', copy: 'For the light-blue scooter, the mountain roads, and the ordinary morning when the handshake is no longer across a screen.' },
];
export default function CouplesSecretHandshakePage() { const [selected, setSelected] = useState(0); const gesture = gestures[selected]; return <main className="min-h-dvh bg-[#e6edf0] px-5 py-12 text-[#253940] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-cyan-900/15 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-cyan-700"><Hand className="h-4 w-4" /> Abu & Bhuntu private code</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">A secret handshake made of things only we notice.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#5c747b]">Four gestures of care, kept safe for Samjhana and Abu.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Private gestures">{gestures.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-cyan-700 bg-white shadow-xl' : 'border-cyan-900/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-cyan-700">{item.label}</span><span className="mt-3 block text-xl font-black">{item.title}</span></button>)}</nav><section className="rounded-[2rem] bg-[#f7ffff] p-8 shadow-[15px_18px_0_rgba(37,57,64,.12)] sm:p-14"><LockKeyhole className="h-9 w-9 text-cyan-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-cyan-700">Gesture 0{selected + 1} · private code</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{gesture.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#5c747b]">{gesture.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-cyan-900/15 pt-6 text-sm font-black text-cyan-700"><Heart className="h-4 w-4 fill-current text-rose-400" /><Sparkles className="h-4 w-4" /> Kept between Abu and his Bhuntu.</div></section></div></div></main>; }
