import React, { useState } from 'react';
import { CloudSun, Heart, Moon, SunMedium } from 'lucide-react';

const signals = [
  { label: 'Morning signal', title: 'A little light is on your side.', copy: 'Start with one small joy. Abu hopes Samjhana remembers that she does not need a dramatic reason to deserve a beautiful day.', icon: SunMedium, tone: 'bg-amber-50' },
  { label: 'Afternoon signal', title: 'A message may change the weather.', copy: 'A call, a remembered detail, or a nickname from Abu can turn an ordinary hour into a softer one.', icon: CloudSun, tone: 'bg-sky-50' },
  { label: 'Evening signal', title: 'The distance is quieter tonight.', copy: 'Nepalgunj and Sakai remain far on the map, but the care inside the conversation is still close.', icon: Moon, tone: 'bg-indigo-50' },
  { label: 'Future signal', title: 'A road is waiting for both of you.', copy: 'Bardiya, Pokhara, Manang, Mustang, and the light-blue scooter are all signs that the story has more chapters.', icon: Heart, tone: 'bg-emerald-50' },
];
export default function CoupleDailyHoroscopePage() { const [selected, setSelected] = useState(0); const signal = signals[selected]; const Icon = signal.icon; return <main className="min-h-dvh bg-[#eeeaf6] px-5 py-12 text-[#302d49] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-violet-900/15 pb-8"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-violet-700">Abu’s emotional weather desk</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Today’s forecast has a very familiar name in it.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#6d6285]">Four signals for the day, written as reminders rather than predictions.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Emotional weather signals">{signals.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-violet-700 bg-white shadow-xl' : 'border-violet-900/10 bg-white/45 hover:bg-white/80'}`}><span className="flex items-center gap-3"><item.icon className="h-5 w-5 text-violet-700" /><span className="text-xl font-black">{item.label}</span></span></button>)}</nav><section className={`rounded-[2rem] ${signal.tone} p-8 shadow-[15px_18px_0_rgba(48,45,73,.12)] sm:p-14`}><Icon className="h-9 w-9 text-violet-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-violet-700">{signal.label}</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{signal.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#6d6285]">{signal.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-violet-900/15 pt-6 text-sm font-black text-violet-700"><Heart className="h-4 w-4 fill-current text-rose-400" /> Abu’s certainty: Samjhana is loved today.</div></section></div></div></main>; }
