import React, { useState } from 'react';
import { ArrowRight, Heart, MapPin, Navigation } from 'lucide-react';

const directions = [
  { label: 'To Dhamboji', copy: 'The first direction Abu would point: back to the streets where ordinary days started becoming ours.', mark: 'origin' },
  { label: 'To Bageshwori', copy: 'The direction of a blessing, a quiet thought, and the hope that every road keeps bringing us closer.', mark: 'blessing' },
  { label: 'To Sakai', copy: 'The direction your voice travels from, crossing the map faster than Abu can miss you.', mark: 'you' },
];

export default function CupidArcheryPage() {
  const [selected, setSelected] = useState(0);
  const direction = directions[selected];
  return <main className="min-h-dvh bg-[#f3ebe1] px-5 py-12 text-[#34251f] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-[#8e5e45]/20 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-[#9b5d40]"><Navigation className="h-4 w-4" /> Abu’s direction notes</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Every road keeps pointing back to you.</h1></div><p className="max-w-xs text-sm leading-7 text-[#765548]">Three directions, one emotional compass: the places and promises that keep Samjhana close.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Choose a direction note">{directions.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-[#9b5d40] bg-white shadow-xl' : 'border-[#8e5e45]/15 bg-white/40 hover:bg-white/75'}`}><span className="flex items-center justify-between text-[10px] font-black uppercase tracking-[0.2em] text-[#9b5d40]"><span>Direction 0{index + 1}</span><span>{item.mark}</span></span><span className="mt-4 block text-xl font-black">{item.label}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#34251f] p-8 text-[#fff8ef] shadow-2xl sm:p-14"><div className="absolute right-10 top-10 h-32 w-32 rounded-full border border-amber-100/20" /><Heart className="h-10 w-10 fill-rose-300 text-rose-300" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-amber-200">{direction.mark} · Abu’s compass</p><h2 className="mt-5 text-5xl font-black tracking-[-0.08em] sm:text-8xl">{direction.label}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-white/75">{direction.copy}</p><button type="button" onClick={() => setSelected((selected + 1) % directions.length)} className="mt-10 inline-flex items-center gap-2 rounded-full bg-amber-200 px-5 py-3 text-sm font-black text-[#34251f] transition hover:-translate-y-1 active:scale-[.98]">Follow the next direction <ArrowRight className="h-4 w-4" /></button><MapPin className="absolute bottom-8 right-10 h-7 w-7 text-amber-200/50" /></section></div></div></main>;
}
