import React, { useState } from 'react';
import { Flower2, Heart, MapPin } from 'lucide-react';

const roses = [
  { name: 'The Dhamboji rose', promise: 'I will keep choosing you in the ordinary hours, not only in the grand ones.', detail: 'A flower for the streets and small food stops that became part of our beginning.', color: 'from-rose-100 to-orange-50' },
  { name: 'The Sakai rose', promise: 'I will make distance a route we travel together, never a reason to feel alone.', detail: 'A flower pressed between Nepalgunj and Osaka, where every call carries home.', color: 'from-violet-100 to-sky-50' },
  { name: 'The future rose', promise: 'I will save room for Bardiya, Pokhara, Manang, Mustang, and every road after them.', detail: 'A flower for the light-blue scooter and the places still waiting for Abu and Sanu.', color: 'from-emerald-100 to-teal-50' },
];
export default function EnchantedRoseGardenPage() { const [active, setActive] = useState(0); const rose = roses[active]; return <main className="min-h-dvh bg-[#13261d] px-5 py-12 text-[#fff9e8] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex items-end justify-between border-b border-[#d9bd72]/35 pb-8"><div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-[#d9bd72]">A private botanical archive · Abu for Samjhana</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Three roses. Three promises. One garden.</h1></div><Flower2 className="h-14 w-14 text-[#d9bd72]" /></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr]"><nav className="space-y-3" aria-label="Rose archive"><p className="mb-5 max-w-sm text-sm leading-7 text-[#c8c8af]">Choose a pressed bloom. The garden opens a different page of the letter each time.</p>{roses.map((item, index) => <button key={item.name} type="button" onClick={() => setActive(index)} className={`w-full rounded-xl border p-5 text-left transition ${active === index ? 'border-[#d9bd72] bg-[#d9bd72]/15' : 'border-[#fff9e8]/15 bg-white/5 hover:bg-white/10'}`}><span className="flex items-center justify-between"><span className="font-black">{item.name}</span><span className="text-xs text-[#d9bd72]">0{index + 1}</span></span><span className="mt-2 block text-sm text-[#c8c8af]">{item.detail}</span></button>)}</nav><section className={`min-h-[29rem] rounded-[2rem] bg-gradient-to-br ${rose.color} p-8 text-[#34251f] shadow-[12px_12px_0_rgba(217,189,114,.22)] sm:p-14`}><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[0.25em] text-[#925157]">Specimen 0{active + 1} · still growing</span><Heart className="h-6 w-6 fill-[#b84c67] text-[#b84c67]" /></div><div className="mt-20 max-w-3xl"><h2 className="text-5xl font-black leading-[.92] tracking-[-0.07em] sm:text-7xl">{rose.promise}</h2><p className="mt-8 max-w-xl text-lg leading-8 text-[#664b43]">{rose.detail}</p></div><div className="mt-16 flex items-center gap-2 border-t border-[#34251f]/20 pt-5 text-sm font-bold text-[#664b43]"><MapPin className="h-4 w-4 text-[#925157]" /> Planted between Nepalgunj and Sakai, for Sanzu</div></section></div></div></main>;
}
