import React, { useState } from 'react';
import { Compass, Home, MapPin, Mountain } from 'lucide-react';

const rooms = [
  { label: 'The arrival room', place: 'Nepalgunj', copy: 'A doorway wide enough for every story from Dhamboji, Bageshwori Temple, the Water Park, and the first days that made Abu feel like home.', icon: Home },
  { label: 'The road room', place: 'Bardiya → Pokhara', copy: 'A wall of windows for a light-blue scooter, roadside tea, and the kind of laughter that makes a long route feel short.', icon: Compass },
  { label: 'The mountain room', place: 'Manang → Mustang', copy: 'A quiet corner reserved for cold air, shared blankets, and the future photographs Abu wants to take with Samjhana.', icon: Mountain },
];
export default function FutureHouseBuilderPage() { const [room, setRoom] = useState(0); const selected = rooms[room]; const Icon = selected.icon; return <main className="min-h-dvh bg-[#dbe5e6] px-5 py-12 text-[#22343a] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="grid gap-8 border-b border-[#22343a]/20 pb-9 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-[#557a82]">Future home plans · drawn by Abu</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">A home is also every place we promise to reach.</h1></div><div className="rounded-full border border-[#557a82]/30 p-5"><Home className="h-10 w-10 text-[#557a82]" /></div></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Future home rooms"><p className="mb-6 max-w-sm text-sm leading-7 text-[#557a82]">This is not a floor plan. It is a small atlas of the life Abu wants to keep making room for.</p>{rooms.map((item, index) => <button key={item.label} type="button" onClick={() => setRoom(index)} className={`w-full border-l-4 p-5 text-left transition ${room === index ? 'border-[#d06f52] bg-white shadow-lg' : 'border-[#9db6b9] bg-white/45 hover:bg-white/80'}`}><span className="flex items-center gap-3"><item.icon className="h-5 w-5 text-[#557a82]" /><span className="font-black">{item.label}</span></span><span className="mt-2 block text-sm text-[#557a82]">{item.place}</span></button>)}</nav><section className="relative min-h-[30rem] overflow-hidden bg-[#f8f7f0] p-8 shadow-[12px_12px_0_rgba(34,52,58,.15)] sm:p-14"><div className="absolute inset-x-8 top-8 border-t border-dashed border-[#557a82]/40" /><div className="absolute bottom-8 left-8 right-8 border-b border-dashed border-[#557a82]/40" /><div className="relative flex h-full min-h-[25rem] flex-col justify-between"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-[#d06f52]">Blueprint note 0{room + 1}</p><h2 className="mt-5 text-5xl font-black tracking-[-0.07em] sm:text-7xl">{selected.place}</h2></div><Icon className="h-9 w-9 text-[#d06f52]" /></div><p className="max-w-2xl text-2xl leading-9 text-[#557a82]">{selected.copy}</p><div className="flex items-center gap-2 border-t border-[#22343a]/15 pt-5 text-sm font-bold text-[#557a82]"><MapPin className="h-4 w-4 text-[#d06f52]" /> Reserved for Abu + Sanu</div></div></section></div></div></main>;
}
