import React, { useState } from 'react';
import { House, LampDesk, Trees } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function FutureHouseBuilderSecondPage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [room, setRoom] = useState('window'); const photo = getAssetUrl(ALL_MEDIA_PHOTOS[132 % ALL_MEDIA_PHOTOS.length]); const rooms = { window: 'A window for the Sakai nights when we still live apart.', kitchen: 'A small kitchen for Chau-Chau, panipuri stories, and the meals we will invent.', garden: 'A quiet garden before the road to Bardiya begins.' };
  return <main className="min-h-[76dvh] bg-[#e8f0ea] px-5 py-12 text-[#24382b] sm:px-10"><div className="mx-auto max-w-6xl"><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><section><p className="text-xs font-black uppercase tracking-[.3em] text-emerald-700/70">A home plan in three small scenes</p><h1 className="mt-5 text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5f7767]">Abu is not building a perfect house. He is saving places for the ordinary things that will make it ours.</p><img src={photo} alt="A future home memory" className="mt-8 h-64 w-full rounded-[2rem] object-cover shadow-xl" loading="lazy" /></section><section className="rounded-[2rem] border border-emerald-200 bg-white p-7 shadow-xl"><House className="h-7 w-7 text-emerald-700" /><div className="mt-7 grid grid-cols-3 gap-2">{Object.keys(rooms).map((item) => <button type="button" key={item} onClick={() => setRoom(item)} className={room === item ? 'rounded-xl bg-emerald-700 px-3 py-3 text-xs font-black text-white' : 'rounded-xl border border-emerald-100 px-3 py-3 text-xs font-black text-emerald-700'}>{item}</button>)}</div><div className="mt-8 rounded-2xl bg-[#eef7ef] p-6"><div className="flex gap-3 text-emerald-700">{room === 'garden' ? <Trees /> : <LampDesk />}<p className="text-xl font-black leading-8">{rooms[room]}</p></div><p className="mt-5 text-sm leading-7 text-[#5f7767]">{gift.message}<br />{gift.gift} {gift.surprise}</p></div></section></div></div></main>;
}
