import React, { useState } from 'react';
import { Globe2, Heart, Orbit, Sparkles } from 'lucide-react';

const orbits = [
  { name: 'Origin orbit', copy: 'Dhamboji and Bageshwori: the first cluster of places that began making ordinary days feel like ours.', tone: 'bg-rose-950' },
  { name: 'Distance orbit', copy: 'Nepalgunj and Sakai: two points that kept a line of light open through every call.', tone: 'bg-indigo-950' },
  { name: 'Joy orbit', copy: 'Chau-Chau, Panipuri, and the small meals that became brighter because they were remembered together.', tone: 'bg-amber-950' },
  { name: 'Future orbit', copy: 'Bardiya, Pokhara, Manang, Mustang, and the road still waiting for our names.', tone: 'bg-emerald-950' },
];

export default function GrandLoveGalaxy3DPage() { const [selected, setSelected] = useState(0); const orbit = orbits[selected]; return <main className="min-h-dvh bg-[#080b17] px-5 py-12 text-white sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-white/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-violet-200"><Globe2 className="h-4 w-4" /> Abu’s private galaxy map</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">A universe built from the places I love because they contain you.</h1></div><p className="max-w-xs text-sm leading-7 text-white/60">Four orbits around one constant: Samjhana at the centre of every good direction.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Galaxy orbits">{orbits.map((item, index) => <button key={item.name} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-violet-200/70 bg-white/10 shadow-xl' : 'border-white/10 bg-white/5 hover:bg-white/10'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-violet-200">Orbit 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.name}</span></button>)}</nav><section className={`relative overflow-hidden rounded-[2rem] ${orbit.tone} p-8 shadow-2xl sm:p-14`}><div className="absolute inset-0 opacity-30"><div className="absolute left-1/4 top-1/4 h-2 w-2 rounded-full bg-white shadow-[0_0_30px_10px_rgba(255,255,255,.8)]" /><div className="absolute right-1/4 top-1/2 h-1 w-1 rounded-full bg-white shadow-[0_0_20px_8px_rgba(255,255,255,.8)]" /><div className="absolute bottom-1/4 left-1/2 h-1 w-1 rounded-full bg-white shadow-[0_0_20px_8px_rgba(255,255,255,.8)]" /></div><Orbit className="relative h-10 w-10 text-violet-200" /><p className="relative mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-violet-200">{orbit.name} · Abu remembers</p><h2 className="relative mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">Samjhana at the centre.</h2><p className="relative mt-7 max-w-xl text-xl leading-8 text-white/70">{orbit.copy}</p><div className="relative mt-10 flex items-center gap-3 border-t border-white/15 pt-6 text-sm font-black text-violet-100"><Heart className="h-4 w-4 fill-current text-rose-300" /><Sparkles className="h-4 w-4" /> Abu’s favourite star is not far away.</div></section></div></div></main>; }
