import React, { useState } from 'react';
import { CupSoda, Heart, MapPin, Phone } from 'lucide-react';

const blends = [
  { name: 'Dhamboji dusk', detail: 'black tea, brown sugar, and the warmth of a long conversation', note: 'For the evenings when Abu wants Nepalgunj to feel close to Sakai.', color: 'bg-[#f4d7bd]' },
  { name: 'Sakai morning', detail: 'jasmine, milk, and a quiet promise to call after class', note: 'For Samjhana’s gentle starts and the voice Abu waits to hear.', color: 'bg-[#d7e7dc]' },
  { name: 'Bhoot’s secret cup', detail: 'strawberry pearls, extra sweetness, absolutely no serious face', note: 'For the Sanzu who can turn one silly nickname into a whole evening.', color: 'bg-[#e7d7ee]' },
];
export default function HeartBubbleTeaMakerPage() { const [blend, setBlend] = useState(0); const chosen = blends[blend]; return <main className="min-h-dvh bg-[#fbf5ec] px-5 py-10 text-[#30261f] sm:px-10 sm:py-16"><div className="mx-auto max-w-6xl"><header className="flex flex-col justify-between gap-8 border-b-2 border-[#30261f] pb-8 md:flex-row md:items-end"><div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-[#a85f45]">The long-distance tea counter · 01</p><h1 className="mt-4 max-w-3xl text-5xl font-black leading-[.92] tracking-[-0.07em] sm:text-8xl">One cup for each side of the map.</h1></div><CupSoda className="h-16 w-16 text-[#a85f45]" /></header><div className="grid gap-10 py-12 lg:grid-cols-[.8fr_1.2fr]"><aside><p className="max-w-sm text-lg leading-8 text-[#745e50]">A tiny tea counter for the days when Abu cannot hand Samjhana a cup in person. Choose the feeling, then read the label beneath it.</p><div className="mt-9 space-y-3">{blends.map((item, index) => <button key={item.name} type="button" onClick={() => setBlend(index)} className={`w-full rounded-xl border-2 p-5 text-left transition ${blend === index ? 'border-[#a85f45] bg-white shadow-[5px_5px_0_#a85f45]' : 'border-[#d8c4b5] bg-transparent hover:bg-white/70'}`}><span className="flex items-center justify-between"><span className="font-black">{item.name}</span><span className="text-xs text-[#a85f45]">0{index + 1}</span></span><span className="mt-2 block text-sm text-[#745e50]">{item.detail}</span></button>)}</div></aside><section className={`${chosen.color} relative min-h-[30rem] overflow-hidden rounded-[2rem] p-8 sm:p-14`}><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full border-[30px] border-white/35" /><div className="absolute -bottom-32 -left-16 h-72 w-72 rounded-full border-[38px] border-white/25" /><div className="relative flex h-full flex-col justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-[#745e50]"><MapPin className="h-4 w-4" /> Nepalgunj ↔ Sakai</div><p className="mt-20 text-sm font-black uppercase tracking-[0.2em] text-[#a85f45]">Now pouring</p><h2 className="mt-3 text-5xl font-black leading-none tracking-[-0.07em] sm:text-7xl">{chosen.name}</h2><p className="mt-6 max-w-lg text-xl leading-8 text-[#59463a]">{chosen.note}</p></div><div className="mt-16 flex items-center justify-between border-t border-[#30261f]/20 pt-6"><span className="text-sm font-bold text-[#745e50]">Shared by Abu · saved for Samjhana</span><Phone className="h-6 w-6 text-[#a85f45]" /></div></div></section></div><footer className="flex items-center gap-2 border-t border-[#30261f]/20 pt-6 text-sm font-black text-[#a85f45]"><Heart className="h-4 w-4 fill-current" /> A sweet cup, even across two time zones.</footer></div></main>; }
