import React, { useState } from 'react';
import { BookMarked, ChevronRight, MailOpen } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function LoveLetterArchiveVaultPage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [letter, setLetter] = useState(0); const photo = getAssetUrl(ALL_MEDIA_PHOTOS[102 % ALL_MEDIA_PHOTOS.length]); const tabs = ['When Sakai feels far away', 'When your birthday feels quiet', 'When Abu owes you a hug'];
  return <main className="min-h-[76dvh] bg-[#f7f0e4] px-5 py-12 text-[#392b25] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.3em] text-[#a26e58]">Archive drawer 02</p><h1 className="mt-5 text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1></div><BookMarked className="h-12 w-12 text-[#a26e58]" /></div><div className="mt-12 grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><nav className="space-y-3">{tabs.map((tab, i) => <button type="button" key={tab} onClick={() => setLetter(i)} className={letter === i ? 'flex w-full items-center gap-3 rounded-2xl bg-[#392b25] p-5 text-left text-[#fff8ec]' : 'flex w-full items-center gap-3 rounded-2xl border border-[#e2d4c2] bg-white/70 p-5 text-left'}><MailOpen className="h-5 w-5 shrink-0 text-[#a26e58]" /><span className="font-bold leading-6">{tab}</span><ChevronRight className="ml-auto h-4 w-4" /></button>)}</nav><section className="rounded-[2rem] border border-[#e2d4c2] bg-white p-7 shadow-xl sm:p-10"><img src={photo} alt="A letter archive memory" className="h-52 w-full rounded-2xl object-cover" loading="lazy" /><p className="mt-7 text-xs font-black uppercase tracking-[.2em] text-[#a26e58]">{tabs[letter]}</p><h2 className="mt-4 text-3xl font-black">{gift.memory}</h2><p className="mt-5 leading-8 text-[#735f53]">{gift.message}</p><p className="mt-6 border-t border-[#eadfd0] pt-5 text-sm leading-7 text-[#735f53]">{gift.gift} {gift.surprise}</p></section></div></div></main>;
}
