import React, { useState } from 'react';
import { Archive, Heart, Mail } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function LoveJarNotesPage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [note, setNote] = useState(0); const photos = [38, 93, 144].map((i) => getAssetUrl(ALL_MEDIA_PHOTOS[i % ALL_MEDIA_PHOTOS.length])); const notes = ['Open when Sakai feels quiet', 'Open after a difficult day', 'Open when Abu owes you a hug'];
  return <main className="min-h-[76dvh] bg-[#f3e9dc] px-5 py-12 text-[#3c2c28] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[#b05d6b]"><Archive className="h-6 w-6" /><span className="text-xs font-black uppercase tracking-[.3em]">Abu’s keepsake drawer</span></div><h1 className="mt-5 text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#7b625b]">Each note is attached to a real feeling—not a random compliment. Choose the moment you need, Sanu, and let Abu answer from Nepalgunj.</p><div className="mt-12 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><section className="grid grid-cols-3 gap-3">{photos.map((photo) => <img key={photo} src={photo} alt="A keepsake memory" className="h-60 w-full rounded-[1.5rem] object-cover shadow-lg" loading="lazy" />)}</section><section className="rounded-[2rem] border border-rose-200 bg-white/75 p-7 shadow-xl"><div className="flex flex-wrap gap-2">{notes.map((item, i) => <button type="button" key={item} onClick={() => setNote(i)} className={note === i ? 'rounded-full bg-[#b05d6b] px-4 py-2 text-xs font-black text-white' : 'rounded-full border border-rose-200 px-4 py-2 text-xs font-black text-[#b05d6b]'}>{item}</button>)}</div><div className="mt-9 rounded-[1.5rem] bg-[#fff6f2] p-6"><Mail className="h-6 w-6 text-[#b05d6b]" /><p className="mt-5 text-2xl font-black leading-8">{gift.message}</p><p className="mt-5 text-sm leading-7 text-[#7b625b]">{gift.memory} {gift.compliment}</p><div className="mt-6 flex items-center gap-2 border-t border-rose-100 pt-5 text-sm font-bold text-[#b05d6b]"><Heart className="h-4 w-4 fill-current" />{gift.gift} {gift.surprise}</div></div></section></div></div></main>;
}
