import React, { useState } from 'react';
import { FlaskConical, Heart, Leaf, Sparkles } from 'lucide-react';

const ingredients = [
  { name: 'The first “Abu”', detail: 'One nickname, added gently, until it became the name Abu hopes to hear for a very long time.', color: 'bg-rose-50' },
  { name: 'Dhamboji evenings', detail: 'A measure of familiar streets, shared foods, and the ordinary moments that quietly became ours.', color: 'bg-amber-50' },
  { name: 'Nepalgunj–Sakai calls', detail: 'A little distance, a lot of patience, and the decision to keep showing up for each other.', color: 'bg-sky-50' },
  { name: 'Future mountain roads', detail: 'Bardiya, Pokhara, Manang, Mustang, and the light-blue scooter waiting at the edge of the recipe.', color: 'bg-emerald-50' },
];
export default function LovePotionBreweryPage() { const [selected, setSelected] = useState(0); const ingredient = ingredients[selected]; return <main className="min-h-dvh bg-[#202719] px-5 py-12 text-[#f4f0dc] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-lime-100/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-lime-200"><FlaskConical className="h-4 w-4" /> Abu’s relationship recipe cabinet</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">The secret ingredient was always choosing you.</h1></div><p className="max-w-xs text-sm leading-7 text-white/60">A cabinet of real details, not a magic formula. Love is made from what we keep remembering.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1" aria-label="Recipe ingredients">{ingredients.map((item, index) => <button key={item.name} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-5 text-left transition ${selected === index ? 'border-lime-200/70 bg-white/10 shadow-xl' : 'border-white/10 bg-white/5 hover:bg-white/10'}`}><span className="flex items-center gap-3"><Leaf className="h-5 w-5 text-lime-200" /><span className="text-lg font-black">{item.name}</span></span><span className="mt-3 block text-[10px] font-black uppercase tracking-[0.18em] text-white/45">Ingredient 0{index + 1}</span></button>)}</nav><section className={`relative overflow-hidden rounded-[2rem] ${ingredient.color} p-8 text-[#27331f] shadow-[15px_18px_0_rgba(0,0,0,.25)] sm:p-14`}><div className="absolute right-10 top-10 h-24 w-24 rounded-full border border-lime-900/20" /><Sparkles className="h-10 w-10 text-lime-800" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-lime-800">Ingredient 0{selected + 1} · Abu remembers</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{ingredient.name}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#526047]">{ingredient.detail}</p><div className="mt-10 flex items-center gap-3 border-t border-lime-900/15 pt-6 text-sm font-black text-lime-800"><Heart className="h-4 w-4 fill-current text-rose-500" /> Brewed slowly for my Bhuntu.</div></section></div></div></main>; }
