import React, { useState } from 'react';
import { Camera, Eye, Layers } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function LoveScratchOffGallerySecondPage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [revealed, setRevealed] = useState(0); const photos = [15, 74, 123].map((i) => getAssetUrl(ALL_MEDIA_PHOTOS[i % ALL_MEDIA_PHOTOS.length]));
  return <main className="min-h-[76dvh] bg-[#202024] px-5 py-12 text-[#f7f4ee] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-amber-200"><Layers className="h-6 w-6" /><span className="text-xs font-black uppercase tracking-[.3em]">Gallery layer 02</span></div><h1 className="mt-5 max-w-4xl text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/60">Every photo is a surface. Abu left a sentence beneath each one for the moment you decide to look closer.</p><div className="mt-12 grid gap-5 md:grid-cols-3">{photos.map((photo, i) => <button type="button" key={photo} onClick={() => setRevealed(i)} className={revealed === i ? 'rounded-[2rem] border-2 border-amber-200 bg-[#2d2d34] p-3 text-left' : 'rounded-[2rem] border border-white/10 bg-[#29292e] p-3 text-left'}><img src={photo} alt="A hidden birthday memory" className="h-64 w-full rounded-[1.5rem] object-cover" loading="lazy" /><p className="mt-4 px-2 text-xs font-black uppercase tracking-[.18em] text-amber-200/70">{revealed === i ? 'Note uncovered' : 'Look beneath this memory'}</p><p className="mt-2 px-2 pb-2 text-lg font-black">{i === revealed ? gift.memory : <Camera className="h-5 w-5 text-white/40" />}</p></button>)}</div><section className="mt-10 rounded-[2rem] border border-amber-200/20 bg-amber-100/[.06] p-7"><div className="flex gap-3 text-amber-200"><Eye className="h-5 w-5" /><p className="text-sm leading-7 text-white/70">{gift.message} {gift.gift} {gift.surprise}</p></div></section></div></main>;
}
