import React, { useState } from 'react';
import { Heart, Map, Send, Stamp } from 'lucide-react';

const stamps = [
  { place: 'Dhamboji', caption: 'Postmarked: where it began', copy: 'A first stamp for the streets and small memories that helped Abu understand the shape of this story.' },
  { place: 'Sakai, Osaka', caption: 'Postmarked: where your voice lives', copy: 'A stamp for every call that travelled farther than a letter and still arrived exactly where Abu needed it.' },
  { place: 'Bageshwori', caption: 'Postmarked: with a blessing', copy: 'A quiet place on the album page for hope, patience, and the promise to keep choosing each other.' },
  { place: 'Mustang', caption: 'Postmarked: future delivery', copy: 'A stamp not yet used, saved for the road where the light-blue scooter and both our names finally share a frame.' },
];

export default function LoveStampCollectionPage() { const [selected, setSelected] = useState(0); const stamp = stamps[selected]; return <main className="min-h-dvh bg-[#dae4e1] px-5 py-12 text-[#203936] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-emerald-900/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-emerald-700"><Stamp className="h-4 w-4" /> Abu’s postage album</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Every place gets a stamp. Every stamp returns to you.</h1></div><p className="max-w-xs text-sm leading-7 text-[#5a756d]">A travel album for the origin, the distance, the blessing, and the future road.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="grid gap-3 sm:grid-cols-2" aria-label="Travel postage stamps">{stamps.map((item, index) => <button key={item.place} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-5 text-left transition ${selected === index ? 'border-emerald-700 bg-white shadow-xl' : 'border-emerald-900/10 bg-white/45 hover:bg-white/80'}`}><span className="grid h-10 w-10 place-items-center rounded border-2 border-dashed border-emerald-700/40"><Map className="h-5 w-5 text-emerald-700" /></span><span className="mt-5 block text-xl font-black">{item.place}</span><span className="mt-2 block text-[10px] font-black uppercase tracking-[0.18em] text-[#5a756d]">Stamp 0{index + 1}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#f5f1e7] p-8 shadow-[15px_18px_0_rgba(32,57,54,.12)] sm:p-14"><div className="absolute right-10 top-10 rotate-6 rounded border-2 border-dashed border-emerald-700/40 p-4"><Send className="h-8 w-8 text-emerald-700" /></div><Heart className="h-10 w-10 fill-rose-300 text-rose-500" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">{stamp.caption}</p><h2 className="mt-5 text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{stamp.place}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#5a756d]">{stamp.copy}</p><div className="mt-10 border-t border-emerald-900/15 pt-6 text-sm font-black text-emerald-700">Addressed to Samjhana · sent by Abu</div></section></div></div></main>; }
