import React, { useState } from 'react';
import { Blocks, Heart, MapPin, Sparkles } from 'lucide-react';

const tiles = [
  { label: 'A nickname', copy: 'Abu', color: 'bg-rose-200' },
  { label: 'A starting point', copy: 'Dhamboji', color: 'bg-amber-200' },
  { label: 'A shared table', copy: 'Panipuri', color: 'bg-emerald-200' },
  { label: 'A future road', copy: 'Mustang', color: 'bg-sky-200' },
];

export default function LovePixelArtCreatorPage() { const [selected, setSelected] = useState(0); const tile = tiles[selected]; return <main className="min-h-dvh bg-[#20252b] px-5 py-12 text-[#f4f0e8] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-white/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-lime-300"><Blocks className="h-4 w-4" /> Abu’s memory mosaic</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Tiny squares. A very large love.</h1></div><p className="max-w-xs text-sm leading-7 text-white/60">Each tile is a detail. Together they make the picture Abu keeps seeing when he thinks of Samjhana.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="grid gap-3 sm:grid-cols-2" aria-label="Choose a memory tile">{tiles.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-5 text-left transition ${selected === index ? 'border-lime-300 bg-white/10 shadow-xl' : 'border-white/10 bg-white/5 hover:bg-white/10'}`}><span className={`grid h-10 w-10 place-items-center rounded ${item.color}`}><span className="h-3 w-3 bg-[#20252b]" /></span><span className="mt-5 block text-[10px] font-black uppercase tracking-[0.18em] text-lime-300">Tile 0{index + 1} · {item.label}</span><span className="mt-2 block text-xl font-black">{item.copy}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#f4f0e8] p-8 text-[#20252b] shadow-2xl sm:p-14"><div className="grid grid-cols-4 gap-2 opacity-20">{Array.from({ length: 32 }, (_, index) => <span key={index} className={`aspect-square rounded ${index % 5 === selected ? tile.color : 'bg-slate-400'}`} />)}</div><Sparkles className="mt-12 h-9 w-9 text-lime-700" /><p className="mt-8 text-[10px] font-black uppercase tracking-[0.22em] text-lime-700">Selected tile · {tile.label}</p><h2 className="mt-5 text-6xl font-black tracking-[-0.08em] sm:text-9xl">{tile.copy}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-slate-600">{tile.label === 'A nickname' ? 'A name you gave Abhay, now one of the softest places Abu can live.' : tile.label === 'A starting point' ? 'The first coordinate in the memory mosaic.' : tile.label === 'A shared table' ? 'A small taste that became part of the relationship language.' : 'A future square waiting to be placed beside you.'}</p><div className="mt-10 flex items-center gap-3 border-t border-slate-900/15 pt-6 text-sm font-black text-lime-700"><Heart className="h-4 w-4 fill-current text-rose-500" /><MapPin className="h-4 w-4" /> Abu is still adding details.</div></section></div></div></main>;
}
