import React, { useState } from 'react';
import { Compass, Heart, MapPin, Navigation } from 'lucide-react';

const coordinates = [
  { label: 'Where it began', place: 'Dhamboji', copy: 'The compass starts with familiar streets, Bageshwori memories, and the day Abhay began becoming Abu.', tone: 'bg-rose-50' },
  { label: 'Where the voice lives', place: 'Sakai, Osaka', copy: 'The needle turns toward your voice, your nicknames, and the calls that cross the Nepalgunj–Sakai distance.', tone: 'bg-sky-50' },
  { label: 'Where we will pause', place: 'Pokhara', copy: 'A future direction with lake light, an unhurried photo, and two cups of tea beside the view.', tone: 'bg-emerald-50' },
  { label: 'Where we will keep going', place: 'Manang → Mustang', copy: 'A longer road for the light-blue scooter, a thousand small stops, and your hand finding mine again and again.', tone: 'bg-amber-50' },
];
export default function LoveCompassPage() { const [selected, setSelected] = useState(0); const coordinate = coordinates[selected]; return <main className="min-h-dvh bg-[#e6edf0] px-5 py-12 text-[#20323b] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-slate-700/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-slate-600"><Compass className="h-4 w-4" /> Abu’s emotional compass</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">The needle keeps finding you.</h1></div><p className="max-w-xs text-sm leading-7 text-[#59707b]">Four coordinates, one story: origin, voice, pause, and the road we have not finished.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1" aria-label="Emotional compass coordinates">{coordinates.map((item, index) => <button key={item.place} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-5 text-left transition ${selected === index ? 'border-slate-700 bg-white shadow-xl' : 'border-slate-700/10 bg-white/45 hover:bg-white/80'}`}><span className="flex items-center gap-3"><MapPin className="h-5 w-5 text-slate-600" /><span className="text-lg font-black">{item.place}</span></span><span className="mt-3 block text-[10px] font-black uppercase tracking-[0.18em] text-[#59707b]">Coordinate 0{index + 1} · {item.label}</span></button>)}</nav><section className={`relative overflow-hidden rounded-[2rem] ${coordinate.tone} p-8 shadow-[15px_18px_0_rgba(32,50,59,.12)] sm:p-14`}><div className="absolute right-10 top-10 grid h-20 w-20 place-items-center rounded-full border-4 border-slate-700/15"><Navigation className="h-8 w-8 text-slate-700" /></div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-slate-600">{coordinate.label}</p><h2 className="mt-16 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-8xl">{coordinate.place}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#59707b]">{coordinate.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-slate-700/15 pt-6 text-sm font-black text-slate-700"><Heart className="h-4 w-4 fill-current text-rose-400" /> Abu’s true north is Samjhana.</div></section></div></div></main>; }
