import React, { useState } from 'react';
import { Beaker, Check, FlaskConical } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function LovePotionLab2Page() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [ingredients, setIngredients] = useState([]); const photo = getAssetUrl(ALL_MEDIA_PHOTOS[156 % ALL_MEDIA_PHOTOS.length]); const recipe = [['Patience', 'for the days Nepalgunj and Sakai feel too far apart.'], ['Laughter', 'for the Water Park memories we keep replaying.'], ['Courage', 'for all the places we will still reach together.']];
  return <main className="min-h-[76dvh] bg-[#10231f] px-5 py-12 text-[#effcf2] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-lime-200"><Beaker className="h-7 w-7" /><span className="text-xs font-black uppercase tracking-[.3em]">A gentler kind of laboratory</span></div><h1 className="mt-5 max-w-4xl text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><div className="mt-12 grid gap-8 lg:grid-cols-[1fr_.9fr]"><section className="rounded-[2rem] border border-lime-200/15 bg-white/[.06] p-6"><img src={photo} alt="A memory from Abu’s love laboratory" className="h-60 w-full rounded-[1.5rem] object-contain" loading="lazy" /><div className="mt-7 space-y-3">{recipe.map(([name, caption], i) => <button type="button" key={name} onClick={() => setIngredients((items) => items.includes(i) ? items.filter((item) => item !== i) : [...items, i])} className={ingredients.includes(i) ? 'flex w-full items-center gap-4 rounded-2xl border border-lime-300 bg-lime-100/15 p-4 text-left' : 'flex w-full items-center gap-4 rounded-2xl border border-white/10 p-4 text-left'}><span className="grid h-8 w-8 place-items-center rounded-full bg-lime-200 text-[#10231f]">{ingredients.includes(i) ? <Check className="h-4 w-4" /> : <FlaskConical className="h-4 w-4" />}</span><span><span className="block font-black">{name}</span><span className="mt-1 block text-sm leading-6 text-white/55">{caption}</span></span></button>)}</div></section><aside className="rounded-[2rem] bg-lime-100 p-7 text-[#10231f]"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700/70">The finished mixture</p><h2 className="mt-5 text-3xl font-black">{ingredients.length === 3 ? 'A day made softer for Sanu.' : 'Choose the ingredients Abu would bring.'}</h2><p className="mt-5 leading-8">{ingredients.length === 3 ? gift.message : gift.compliment}</p><p className="mt-6 border-t border-lime-200 pt-5 text-sm leading-7">{gift.gift} {gift.surprise}</p></aside></div></div></main>;
}
