import React, { useState } from 'react';
import { Heart, MessageCircle, Phone, Sparkles } from 'lucide-react';

const languages = [
  { name: 'Words that stay', icon: MessageCircle, copy: '“Abu,” “Babe,” “Bhuntu,” and the small messages that make the day feel intentionally chosen.', color: 'bg-rose-50' },
  { name: 'Time that travels', icon: Phone, copy: 'A call between Nepalgunj and Sakai is not only a conversation. It is Abu making room for you.', color: 'bg-sky-50' },
  { name: 'Details that return', icon: Sparkles, copy: 'Remembering Chau-Chau, Panipuri, the Language Institute, and the things you once mentioned without making a speech about it.', color: 'bg-amber-50' },
  { name: 'Plans that wait', icon: Heart, copy: 'Bardiya, Pokhara, Manang, Mustang, and the light-blue scooter: affection with a future tense.', color: 'bg-emerald-50' },
];

export default function LoveLanguageTestPage() { const [selected, setSelected] = useState(0); const language = languages[selected]; const Icon = language.icon; return <main className="min-h-dvh bg-[#f2efe8] px-5 py-12 text-[#2b302b] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-emerald-900/15 pb-8"><div><p className="text-[10px] font-black uppercase tracking-[0.28em] text-emerald-700">Abu’s communication atlas</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Our language is made of details.</h1></div><p className="max-w-xs text-sm leading-7 text-[#667263]">No test result can contain a relationship. This page simply names the ways Abu keeps saying “I love you.”</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="grid gap-3 sm:grid-cols-2" aria-label="Communication atlas entries">{languages.map((item, index) => <button key={item.name} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-5 text-left transition ${selected === index ? 'border-emerald-700 bg-white shadow-xl' : 'border-emerald-900/10 bg-white/45 hover:bg-white/80'}`}><item.icon className="h-5 w-5 text-emerald-700" /><span className="mt-5 block text-xl font-black">{item.name}</span><span className="mt-2 block text-[10px] font-black uppercase tracking-[0.18em] text-[#667263]">Entry 0{index + 1}</span></button>)}</nav><section className={`relative overflow-hidden rounded-[2rem] ${language.color} p-8 shadow-[15px_18px_0_rgba(43,48,43,.12)] sm:p-14`}><div className="absolute right-10 top-10 h-20 w-20 rounded-full border border-emerald-700/15" /><Icon className="h-10 w-10 text-emerald-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">Entry 0{selected + 1} · Abu means this</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{language.name}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#667263]">{language.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-emerald-900/15 pt-6 text-sm font-black text-emerald-700"><Heart className="h-4 w-4 fill-current text-rose-400" /> Samjhana is Abu’s favourite language.</div></section></div></div></main>; }
