import React, { useState } from 'react';
import { Grid3X3, Heart, RotateCcw } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function LoveMemoryMatch3DPage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [picked, setPicked] = useState([]); const cards = ['The first “huss”', 'Water Park laughter', 'A Sakai night call', 'The road to Bardiya']; const photos = [22, 54, 98, 146].map((i) => getAssetUrl(ALL_MEDIA_PHOTOS[i % ALL_MEDIA_PHOTOS.length]));
  const reset = () => setPicked([]);
  return <main className="min-h-[76dvh] bg-[#f2f7f4] px-5 py-12 text-[#1d3129] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.3em] text-emerald-700/70">A tactile memory table</p><h1 className="mt-5 text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1></div><Grid3X3 className="h-12 w-12 text-emerald-600" /></div><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5e7669]">This room asks you to match a feeling to the moment Abu remembers—not to beat a score, but to notice how many homes our story already has.</p><section className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card, i) => <button type="button" key={card} onClick={() => setPicked((items) => items.includes(i) ? items.filter((item) => item !== i) : [...items, i])} className={picked.includes(i) ? 'rounded-[2rem] border-2 border-emerald-500 bg-white p-3 text-left shadow-lg' : 'rounded-[2rem] border-2 border-transparent bg-white p-3 text-left shadow-lg'}><img src={photos[i]} alt="A memory card" className="h-48 w-full rounded-[1.5rem] object-contain" loading="lazy" /><p className="mt-4 px-2 pb-2 text-lg font-black">{card}</p><p className="px-2 pb-3 text-xs font-bold uppercase tracking-[.16em] text-emerald-700/60">{picked.includes(i) ? 'Feeling found' : 'Turn this memory'}</p></button>)}</section><div className="mt-10 rounded-[2rem] border border-emerald-200 bg-white p-7"><div className="flex items-center gap-3 text-emerald-700"><Heart className="h-5 w-5 fill-current" /><p className="text-sm font-black">{picked.length === 4 ? gift.message : gift.compliment}</p><button type="button" onClick={reset} className="ml-auto rounded-full border border-emerald-200 p-2"><RotateCcw className="h-4 w-4" /></button></div><p className="mt-4 text-sm leading-7 text-[#5e7669]">{gift.gift} {gift.surprise}</p></div></div></main>;
}
