import React, { useState } from 'react';
import { ArrowRight, Heart, MapPin, Sparkles } from 'lucide-react';

const alignments = [
  { label: 'Where it began', left: 'Nepalgunj', right: 'Sakai', copy: 'Different clocks, one instinct: tell each other about the little details before the day is over.', tone: 'bg-[#fff1e8]' },
  { label: 'What always helps', left: 'Chau-Chau', right: 'Panipuri', copy: 'Food is never only food for Abu and Samjhana. It is a shortcut back to laughter, familiar streets, and shared appetite.', tone: 'bg-[#eaf4ec]' },
  { label: 'What comes next', left: 'Light-blue scooter', right: 'Mountain roads', copy: 'The future already has a color, a route, and two names written in the margin: Abu and Sanu.', tone: 'bg-[#e9effb]' },
];
export default function LoveCompatibilityMatrixPage() { const [active, setActive] = useState(0); const item = alignments[active]; return <main className="min-h-dvh bg-[#f2eee7] px-5 py-12 text-[#292c35] sm:px-10 sm:py-16"><div className="mx-auto max-w-6xl"><header className="border-y-2 border-[#292c35] py-8"><div className="flex items-center gap-3 text-[#b35c48]"><Sparkles className="h-5 w-5" /><span className="text-[10px] font-black uppercase tracking-[0.3em]">An alignment chart for Abu + Samjhana</span></div><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Two lives. A surprising number of shared coordinates.</h1></header><div className="grid gap-8 py-12 md:grid-cols-3">{alignments.map((entry, index) => <button key={entry.label} type="button" onClick={() => setActive(index)} className={`min-h-52 rounded-[1.5rem] border-2 p-6 text-left transition ${active === index ? 'border-[#b35c48] shadow-[7px_7px_0_#b35c48]' : 'border-[#292c35]/15 hover:border-[#292c35]/40'}`}><span className="text-[10px] font-black uppercase tracking-[0.22em] text-[#b35c48]">0{index + 1} · {entry.label}</span><span className="mt-10 block text-2xl font-black leading-none">{entry.left}</span><span className="my-3 block h-px w-12 bg-[#b35c48]" /><span className="block text-2xl font-black leading-none">{entry.right}</span></button>)}</div><section className={`${item.tone} rounded-[2rem] p-8 sm:p-14`}><p className="text-[10px] font-black uppercase tracking-[0.25em] text-[#b35c48]">Selected alignment · {item.label}</p><div className="mt-10 flex flex-col items-start gap-5 text-4xl font-black tracking-[-0.06em] sm:flex-row sm:items-center sm:text-6xl"><span>{item.left}</span><ArrowRight className="h-8 w-8 text-[#b35c48] sm:h-10 sm:w-10" /><span>{item.right}</span></div><p className="mt-10 max-w-2xl text-xl leading-8 text-[#5e6068]">{item.copy}</p><div className="mt-12 flex items-center gap-2 border-t border-[#292c35]/15 pt-5 text-sm font-bold text-[#b35c48]"><MapPin className="h-4 w-4" /> Every route still leads back to each other.</div></section><p className="mt-8 flex items-center gap-2 text-sm font-black text-[#b35c48]"><Heart className="h-4 w-4 fill-current" /> Compatibility, Abu’s way: choosing Samjhana again and again.</p></div></main>;
}
