import React, { useState } from 'react';
import { Heart, Magnet, Sparkles } from 'lucide-react';

const poems = [
  { label: 'On ordinary days', text: 'You make the smallest moments stay.', note: 'A line for the food, the walks, and the simple details Abu remembers longer than grand plans.' },
  { label: 'Across the distance', text: 'Two cities, one soft hello.', note: 'A line for Nepalgunj, Sakai, and every call that gives the map a little less power.' },
  { label: 'For the future', text: 'Every road is brighter with you.', note: 'A line for Bardiya, Pokhara, Manang, Mustang, and the light-blue scooter waiting outside the next chapter.' },
];
export default function LovePoetryFridgePage() { const [selected, setSelected] = useState(0); const poem = poems[selected]; return <main className="min-h-dvh bg-[#dce8e9] px-5 py-12 text-[#24363a] sm:px-10 sm:py-16"><div className="mx-auto max-w-6xl"><header className="border-b border-cyan-900/15 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-cyan-700"><Magnet className="h-4 w-4" /> Abu’s poetry fridge</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">The lines I keep where I can see them.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#5c7478]">Three magnetic notes for three ways Samjhana stays on Abu’s mind.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Poetry magnets">{poems.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-cyan-700 bg-white shadow-xl' : 'border-cyan-900/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-cyan-700">Magnet 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.label}</span></button>)}</nav><section className="relative rounded-[2rem] bg-[#fffaf0] p-8 shadow-[15px_18px_0_rgba(36,54,58,.12)] sm:p-14"><div className="absolute right-10 top-8 h-4 w-4 rounded-full bg-rose-400 shadow-[0_0_0_5px_rgba(244,114,182,.15)]" /><Sparkles className="h-9 w-9 text-cyan-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-cyan-700">{poem.label}</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{poem.text}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#5c7478]">{poem.note}</p><div className="mt-10 flex items-center gap-3 border-t border-cyan-900/15 pt-6 text-sm font-black text-cyan-700"><Heart className="h-4 w-4 fill-current text-rose-400" /> Pinned by Abu for his Bhuntu.</div></section></div></div></main>; }
