import React, { useState } from 'react';
import { Feather, WandSparkles } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function LoveSpellCasterStudioPage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [word, setWord] = useState('home'); const photo = getAssetUrl(ALL_MEDIA_PHOTOS[44 % ALL_MEDIA_PHOTOS.length]); const words = ['home', 'huss', 'future', 'Babe'];
  return <main className="min-h-[76dvh] bg-[#261d34] px-5 py-12 text-[#fff4ff] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-violet-200"><WandSparkles className="h-7 w-7" /><span className="text-xs font-black uppercase tracking-[.3em]">Abu’s word studio</span></div><h1 className="mt-5 max-w-4xl text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><div className="mt-12 grid gap-8 lg:grid-cols-[1fr_.9fr]"><section className="rounded-[2rem] border border-violet-200/15 bg-white/[.06] p-6"><img src={photo} alt="A word-making memory" className="h-60 w-full rounded-[1.5rem] object-cover" loading="lazy" /><div className="mt-7 flex flex-wrap gap-2">{words.map((item) => <button type="button" key={item} onClick={() => setWord(item)} className={word === item ? 'rounded-full bg-violet-200 px-4 py-2 text-sm font-black text-[#261d34]' : 'rounded-full border border-white/15 px-4 py-2 text-sm font-black text-white/70'}>{item}</button>)}</div><p className="mt-8 text-3xl font-black leading-tight">{word === 'home' ? 'You are the place Abu’s thoughts return to.' : word === 'huss' ? 'One small word, and a whole conversation begins.' : word === 'future' ? 'A road, a scooter, and you beside Abu.' : 'The name Abu still smiles at before the phone rings.'}</p></section><aside className="rounded-[2rem] bg-violet-100 p-7 text-[#261d34]"><Feather className="h-7 w-7 text-violet-700" /><p className="mt-8 text-xs font-black uppercase tracking-[.2em] text-violet-700/70">The finished line</p><p className="mt-5 text-2xl font-black leading-8">{gift.message}</p><p className="mt-6 border-t border-violet-200 pt-5 text-sm leading-7 text-violet-900/65">{gift.gift} {gift.surprise}</p></aside></div></div></main>;
}
