import React, { useState } from 'react';
import { Gift, Sunrise, Sparkles } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function LoveGrandFinaleSecondPage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [opened, setOpened] = useState(false); const photos = [34, 118, 174].map((i) => getAssetUrl(ALL_MEDIA_PHOTOS[i % ALL_MEDIA_PHOTOS.length]));
  return <main className="min-h-[76dvh] bg-gradient-to-b from-[#ffcf9d] via-[#fff1d9] to-[#f7e9ff] px-5 py-12 text-[#412b32] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[#c66a55]"><Sunrise className="h-7 w-7" /><span className="text-xs font-black uppercase tracking-[.3em]">Another sunrise for Abu and Samjhana</span></div><h1 className="mt-6 max-w-4xl text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#805f67]">The last room does not have to feel like an ending. Abu made this one feel like the morning after every promise.</p><div className="mt-12 grid gap-4 sm:grid-cols-3">{photos.map((photo) => <img key={photo} src={photo} alt="A final birthday memory" className="h-64 w-full rounded-[2rem] object-cover shadow-xl" loading="lazy" />)}</div><section className="mt-10 rounded-[2rem] border border-white/70 bg-white/70 p-8 shadow-xl sm:p-12"><div className="flex items-center gap-3 text-[#c66a55]"><Gift /><p className="text-xs font-black uppercase tracking-[.2em]">The next morning card</p></div><h2 className="mt-5 text-3xl font-black">{gift.memory}</h2><button type="button" onClick={() => setOpened(!opened)} className="mt-8 rounded-full bg-[#412b32] px-6 py-3 text-sm font-black text-white">{opened ? 'Keep this note close' : 'Open Abu’s morning card'}</button>{opened && <div className="mt-8 grid gap-5 border-t border-[#e5c7c0] pt-7 sm:grid-cols-[1fr_auto]"><p className="text-xl font-bold leading-8 text-[#c66a55]">{gift.message}<span className="mt-3 block text-sm font-semibold leading-7 text-[#805f67]">{gift.gift} {gift.surprise}</span></p><Sparkles className="h-10 w-10 text-[#c66a55]" /></div>}</section></div></main>;
}
