import React, { useState } from 'react';
import { ArrowRight, MapPin, Milestone } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function MemoryLanePage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [stop, setStop] = useState(0); const photos = [24, 81, 135].map((i) => getAssetUrl(ALL_MEDIA_PHOTOS[i % ALL_MEDIA_PHOTOS.length])); const stops = [['Dhamboji', 'The city where the first ordinary moments began.'], ['Bageshwori', 'A prayer, a pause, and the feeling that this was becoming real.'], ['Sakai', 'The distance that taught Abu how to stay present.']];
  return <main className="min-h-[76dvh] bg-[#eadfce] px-5 py-12 text-[#342b23] sm:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[#a8623d]"><Milestone className="h-6 w-6" /><span className="text-xs font-black uppercase tracking-[.3em]">A walk through the places that held us</span></div><h1 className="mt-5 text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#765f4d]">This is not a rotating museum card. It is a one-way walk: Dhamboji to Bageshwori to the late-night road between Nepalgunj and Sakai.</p><div className="mt-12 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-[2rem] bg-[#f8f0e5] p-5 shadow-xl"><div className="grid grid-cols-3 gap-3">{photos.map((photo, i) => <img key={photo} src={photo} alt="A real relationship memory" className={i === stop ? 'h-64 w-full rounded-[1.5rem] object-cover ring-4 ring-[#a8623d]' : 'h-64 w-full rounded-[1.5rem] object-cover opacity-70'} loading="lazy" />)}</div><div className="mt-7 flex justify-between gap-2">{stops.map(([place], i) => <button type="button" key={place} onClick={() => setStop(i)} className={stop === i ? 'flex items-center gap-2 rounded-full bg-[#342b23] px-4 py-2 text-xs font-black text-white' : 'flex items-center gap-2 rounded-full border border-[#d7c4ad] px-4 py-2 text-xs font-black text-[#765f4d]'}><MapPin className="h-3 w-3" />{place}</button>)}</div></section><aside className="rounded-[2rem] border border-[#d7c4ad] bg-white/75 p-7"><p className="text-xs font-black uppercase tracking-[.2em] text-[#a8623d]">Stop {stop + 1} of 3</p><h2 className="mt-5 text-3xl font-black">{stops[stop][1]}</h2><p className="mt-5 leading-8 text-[#765f4d]">{gift.memory}. {gift.compliment}</p><button type="button" onClick={() => setStop((stop + 1) % 3)} className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#a8623d] px-5 py-3 text-sm font-black text-white">Walk to the next memory <ArrowRight className="h-4 w-4" /></button><p className="mt-7 border-t border-[#eadfd0] pt-5 text-sm leading-7 text-[#765f4d]">{gift.message} {gift.surprise}</p></aside></div></div></main>;
}
