import React, { useState } from 'react';
import { Anchor, ArrowRight, Heart, Navigation } from 'lucide-react';

const folds = [
  { label: 'The first fold', title: 'Start where the road feels familiar.', copy: 'Dhamboji is not only a place on the map. It is where Abu learned which ordinary corners would become memories worth carrying.' },
  { label: 'The second fold', title: 'Let the water choose the pace.', copy: 'Pokhara waits for a slow morning, a shared view, and the kind of silence that feels comfortable because you are beside me.' },
  { label: 'The last fold', title: 'Leave room for the road ahead.', copy: 'Manang, Mustang, Bardiya—future names for days we have not lived yet, folded carefully inside the same promise.' },
];
export default function OrigamiBoatPage() { const [selected, setSelected] = useState(0); const fold = folds[selected]; return <main className="min-h-dvh bg-[#dff1f1] px-5 py-12 text-[#1d3a40] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-cyan-900/15 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-cyan-700"><Navigation className="h-4 w-4" /> A future folded into paper</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Abu folded a boat for the road to you.</h1></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><nav className="space-y-3" aria-label="Origami travel folds">{folds.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-cyan-700 bg-white shadow-xl' : 'border-cyan-900/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-cyan-700">Fold 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.label}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#1d3a40] p-8 text-[#efffff] shadow-2xl sm:p-14"><div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-cyan-900/50 to-transparent" /><Anchor className="relative h-10 w-10 text-cyan-200" /><p className="relative mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-cyan-200">{fold.label} · Abu’s note</p><h2 className="relative mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{fold.title}</h2><p className="relative mt-7 max-w-xl text-xl leading-8 text-white/75">{fold.copy}</p><button type="button" onClick={() => setSelected((selected + 1) % folds.length)} className="relative mt-10 inline-flex items-center gap-2 rounded-full bg-cyan-200 px-5 py-3 text-sm font-black text-[#1d3a40] transition hover:-translate-y-1 active:scale-[.98]">Fold the next page <ArrowRight className="h-4 w-4" /></button><Heart className="absolute bottom-8 right-10 h-7 w-7 fill-rose-300 text-rose-300" /></section></div></div></main>; }
