import React, { useState } from 'react';
import { Disc3, Heart, Music, Waves } from 'lucide-react';

const movements = [
  { label: 'Movement I', title: 'A room in Dhamboji', copy: 'Warm chords for familiar streets, Bageshwori memories, and the first part of the story.', tone: 'from-amber-100 to-orange-100' },
  { label: 'Movement II', title: 'A table with Panipuri', copy: 'A brighter rhythm for shared food, laughter, and the small joy of wanting the same thing.', tone: 'from-rose-100 to-pink-100' },
  { label: 'Movement III', title: 'Two cities awake', copy: 'A slower melody for Nepalgunj and Sakai, where a call can make two different nights feel close.', tone: 'from-sky-100 to-indigo-100' },
  { label: 'Movement IV', title: 'The road after the distance', copy: 'A future refrain for the light-blue scooter, the mountains, and the ordinary mornings ahead.', tone: 'from-emerald-100 to-teal-100' },
];

export default function RomanticMusicBox2Page() { const [selected, setSelected] = useState(0); const movement = movements[selected]; return <main className="min-h-dvh bg-[#f0e9dc] px-5 py-12 text-[#352b27] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-[#805e4d]/20 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-[#a15f43]"><Disc3 className="h-4 w-4" /> Abu’s second soundtrack cabinet</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">A small box for the music inside the memories.</h1></div><p className="max-w-xs text-sm leading-7 text-[#775d50]">Four movements for the story behind the photos, the calls, and the future plans.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="space-y-3" aria-label="Music-box movements">{movements.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-[#a15f43] bg-white shadow-xl' : 'border-[#805e4d]/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-[#a15f43]">{item.label}</span><span className="mt-3 block text-xl font-black">{item.title}</span></button>)}</nav><section className={`relative overflow-hidden rounded-[2rem] bg-gradient-to-br ${movement.tone} p-8 shadow-[15px_18px_0_rgba(53,43,39,.12)] sm:p-14`}><div className="absolute right-10 top-10 flex items-end gap-2"><span className="h-14 w-1 rounded-full bg-[#a15f43]/30" /><span className="h-24 w-1 rounded-full bg-[#a15f43]/30" /><span className="h-10 w-1 rounded-full bg-[#a15f43]/30" /></div><Music className="h-10 w-10 text-[#a15f43]" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-[#a15f43]">{movement.label} · Abu remembers</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{movement.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#775d50]">{movement.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-[#805e4d]/15 pt-6 text-sm font-black text-[#a15f43]"><Waves className="h-4 w-4" /><Heart className="h-4 w-4 fill-current text-rose-400" /> Kept in Abu’s memory box.</div></section></div></div></main>; }
