import React, { useState } from 'react';
import { Heart, Mail, MessageSquare, Pin } from 'lucide-react';

const messages = [
  { label: 'Pinned from Dhamboji', title: 'I remember the small things.', copy: 'The foods, the walks, the places you mentioned once and thought Abu might forget. I did not.' },
  { label: 'Pinned from Sakai', title: 'Your voice still arrives.', copy: 'No matter how far the map stretches, “Abu” still reaches the part of me that was waiting for you.' },
  { label: 'Pinned for your birthday', title: 'You deserve a room made for you.', copy: 'Not a generic surprise. A whole trail of details, because Samjhana is worth the time it takes to make something carefully.' },
  { label: 'Pinned for the future', title: 'I am saving a seat.', copy: 'For the light-blue scooter, the mountain roads, the tea stops, and the ordinary morning where we do not have to say goodbye.' },
];

export default function RomanticMessageGridPage() { const [selected, setSelected] = useState(0); const message = messages[selected]; return <main className="min-h-dvh bg-[#f0e8db] px-5 py-12 text-[#332822] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-[#7e5946]/20 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-[#9d5e43]"><MessageSquare className="h-4 w-4" /> Abu’s pinned message desk</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Four messages I would pin forever.</h1></div><p className="max-w-xs text-sm leading-7 text-[#765b4d]">A small grid of notes that do not expire when the page closes.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="grid gap-3 sm:grid-cols-2" aria-label="Pinned message cards">{messages.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`relative rounded-2xl border p-5 text-left transition ${selected === index ? 'border-[#9d5e43] bg-white shadow-xl' : 'border-[#7e5946]/10 bg-white/45 hover:bg-white/80'}`}><Pin className="absolute right-4 top-4 h-4 w-4 rotate-45 text-[#9d5e43]" /><span className="block pr-6 text-[10px] font-black uppercase tracking-[0.18em] text-[#9d5e43]">Card 0{index + 1}</span><span className="mt-5 block text-lg font-black">{item.label}</span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#fffaf0] p-8 shadow-[15px_18px_0_rgba(51,40,34,.12)] sm:p-14"><div className="absolute right-10 top-10 rotate-6"><Mail className="h-12 w-12 text-[#9d5e43]/45" /></div><Heart className="h-9 w-9 fill-rose-300 text-rose-500" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-[#9d5e43]">{message.label}</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{message.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#765b4d]">{message.copy}</p><div className="mt-10 border-t border-[#7e5946]/15 pt-6 text-sm font-black text-[#9d5e43]">Pinned by Abu · never to be archived away</div></section></div></div></main>; }
