import React, { useState } from 'react';
import { Heart, LockKeyhole, MapPin, Sparkles } from 'lucide-react';

const windows = [
  { label: 'The first window', title: 'The name Abu keeps hearing', copy: 'Samjhana gave Abhay a name that feels like a small room he can carry anywhere.', tone: 'bg-rose-50' },
  { label: 'The second window', title: 'The place Abu keeps returning to', copy: 'Dhamboji, Bageshwori, the food memories, and the streets where ordinary days became ours.', tone: 'bg-amber-50' },
  { label: 'The third window', title: 'The distance Abu keeps crossing', copy: 'Nepalgunj to Sakai is a line on a map, not a limit on the love inside every call.', tone: 'bg-sky-50' },
  { label: 'The fourth window', title: 'The future Abu keeps opening', copy: 'A light-blue scooter, mountain roads, and the next ordinary morning beside you.', tone: 'bg-emerald-50' },
];

export default function RomanticLocketChangerPage() { const [selected, setSelected] = useState(0); const window = windows[selected]; return <main className="min-h-dvh bg-[#e6d8d1] px-5 py-12 text-[#382a2d] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b border-rose-900/15 pb-8"><div><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-rose-700"><LockKeyhole className="h-4 w-4" /> Abu’s locket archive</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Four windows. One person I keep close.</h1></div><p className="max-w-xs text-sm leading-7 text-[#76565e]">Every window opens onto a different part of the story Abu is grateful to have with Samjhana.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><nav className="grid gap-3 sm:grid-cols-2" aria-label="Locket windows">{windows.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`rounded-2xl border p-5 text-left transition ${selected === index ? 'border-rose-700 bg-white shadow-xl' : 'border-rose-900/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-rose-700">Window 0{index + 1}</span><span className="mt-3 block text-xl font-black">{item.label}</span></button>)}</nav><section className={`relative overflow-hidden rounded-[2rem] ${window.tone} p-8 shadow-[15px_18px_0_rgba(56,42,45,.12)] sm:p-14`}><div className="absolute right-10 top-10 grid h-20 w-20 place-items-center rounded-full border-4 border-rose-700/15"><Heart className="h-8 w-8 fill-rose-300 text-rose-500" /></div><Sparkles className="h-10 w-10 text-rose-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-rose-700">{window.label} · for Samjhana</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{window.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#76565e]">{window.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-rose-900/15 pt-6 text-sm font-black text-rose-700"><MapPin className="h-4 w-4" /> Kept close by Abu.</div></section></div></div></main>; }
