import React, { useState } from 'react';
import { Crown, Heart, Ribbon, Sparkles } from 'lucide-react';

const honors = [
  { title: 'Keeper of soft courage', copy: 'For carrying kindness through difficult days and still finding room to make other people feel safe.', color: 'bg-rose-50' },
  { title: 'Best voice across distance', copy: 'For making “Abu” sound like the warmest place between Nepalgunj and Sakai.', color: 'bg-sky-50' },
  { title: 'Chief architect of our future', copy: 'For making Bardiya, Pokhara, Manang, Mustang, and the light-blue scooter feel like plans instead of fantasies.', color: 'bg-amber-50' },
];
export default function RoyalCrownPage() { const [selected, setSelected] = useState(0); const honor = honors[selected]; return <main className="min-h-dvh bg-[#f1e7d4] px-5 py-12 text-[#37291e] sm:px-10 sm:py-16"><div className="mx-auto max-w-6xl"><header className="text-center"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-[#a16b2d]"><Crown className="h-4 w-4" /> The Samjhana honours room</p><h1 className="mt-5 text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">No crown is bigger than the person wearing it.</h1><p className="mx-auto mt-6 max-w-xl text-sm leading-7 text-[#765f47]">Abu made three recognitions for the qualities that make my Bhuntu impossible to replace.</p></header><div className="mt-12 grid gap-8 md:grid-cols-3">{honors.map((item, index) => <button key={item.title} type="button" onClick={() => setSelected(index)} className={`rounded-[2rem] border-2 border-dashed p-6 text-left transition ${selected === index ? 'border-[#a16b2d] bg-white shadow-xl' : 'border-[#a16b2d]/20 bg-white/35 hover:bg-white/70'}`}><Ribbon className="h-8 w-8 text-[#a16b2d]" /><span className="mt-10 block text-[10px] font-black uppercase tracking-[0.18em] text-[#a16b2d]">Honour 0{index + 1}</span><span className="mt-3 block text-2xl font-black leading-tight">{item.title}</span></button>)}</div><section className={`mt-10 rounded-[2rem] ${honor.color} p-8 text-center shadow-[15px_18px_0_rgba(55,41,30,.12)] sm:p-14`}><Sparkles className="mx-auto h-10 w-10 text-[#a16b2d]" /><p className="mt-8 text-[10px] font-black uppercase tracking-[0.22em] text-[#a16b2d]">Presented by Abu · for Samjhana</p><h2 className="mt-5 text-4xl font-black tracking-[-0.06em] sm:text-6xl">{honor.title}</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#765f47]">{honor.copy}</p><div className="mt-8 flex items-center justify-center gap-2 text-sm font-black text-[#a16b2d]"><Heart className="h-4 w-4 fill-current text-rose-400" /> You are loved beyond every title.</div></section></div></main>; }
