import React, { useState } from 'react';
import { Moon, Sparkles, Star } from 'lucide-react';
import { ALL_MEDIA_PHOTOS, getAssetUrl } from '../utils/mediaUtils';
import { pageGiftByRoute, pageNameByRoute } from '../data/pageGiftData';
import { useLocation } from 'react-router-dom';

export default function StarsPage() {
  const { pathname } = useLocation(); const gift = pageGiftByRoute[pathname] || {}; const page = pageNameByRoute[pathname] || {}; const [selected, setSelected] = useState(0); const photos = [11, 52, 129].map((i) => getAssetUrl(ALL_MEDIA_PHOTOS[i % ALL_MEDIA_PHOTOS.length])); const constellations = [['Sanzu', 'the name that made Abhay into Abu.'], ['Bhuntu', 'the smile that makes Nepalgunj feel softer.'], ['Sanu', 'the future Abu keeps seeing on Bardiya roads.']];
  return <main className="min-h-[76dvh] overflow-hidden bg-[#080d1b] px-5 py-12 text-[#f5f0df] sm:px-10"><div className="mx-auto max-w-6xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><div className="flex items-center gap-3 text-sky-200"><Moon className="h-6 w-6" /><span className="text-xs font-black uppercase tracking-[.28em]">A sky letter for Samjhana</span></div><h1 className="mt-7 text-6xl font-black leading-[.88] tracking-[-.08em] sm:text-8xl">{page.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-sky-100/60">No score, no horoscope, and nothing to solve. Abu made a quiet observatory for the names and memories that make his Sanzu impossible to replace.</p><div className="mt-8 flex flex-wrap gap-2">{constellations.map(([name], i) => <button type="button" key={name} onClick={() => setSelected(i)} className={i === selected ? 'rounded-full bg-amber-200 px-4 py-2 text-xs font-black text-[#080d1b]' : 'rounded-full border border-sky-100/15 px-4 py-2 text-xs font-black text-sky-100/65'}><Star className="mr-1 inline h-3 w-3" />{name}</button>)}</div><p className="mt-6 text-2xl font-black leading-tight text-amber-100">{constellations[selected][1]}</p></div><section className="rounded-[2.5rem] border border-sky-200/15 bg-sky-100/[.04] p-5 shadow-[0_0_100px_rgba(72,128,220,.12)]"><div className="grid grid-cols-2 gap-3"><img src={photos[0]} alt="A birthday memory under Abu’s sky" className="col-span-2 h-64 w-full rounded-[2rem] object-cover" loading="lazy" />{photos.slice(1).map((photo) => <img key={photo} src={photo} alt="A constellation memory" className="h-44 w-full rounded-2xl object-cover" loading="lazy" />)}</div><div className="mt-6 flex gap-3 rounded-2xl bg-[#0f1931] p-5"><Sparkles className="h-5 w-5 shrink-0 text-amber-200" /><p className="text-sm leading-7 text-sky-100/70">{gift.message} {gift.surprise}</p></div></section></div></div></main>;
}
