import React, { useState } from 'react';
import { Coffee, Heart, Leaf, Sparkles } from 'lucide-react';

const cups = [
  { label: 'Cup one · origin', title: 'A warm start', copy: 'For the day a yes changed the calendar and Abhay began becoming Abu.' },
  { label: 'Cup two · distance', title: 'A patient steep', copy: 'For Nepalgunj, Sakai, and the calls that become sweeter because they were waited for.' },
  { label: 'Cup three · birthday', title: 'A little sweetness', copy: 'For Samjhana’s birthday, this first gift, and every name Abu loves calling her.' },
  { label: 'Cup four · future', title: 'A shared table', copy: 'For Bardiya, Pokhara, Manang, Mustang, and mornings when the tea is already beside you.' },
];
export default function SweetTeaCeremonyPage() { const [selected, setSelected] = useState(0); const cup = cups[selected]; return <main className="min-h-dvh bg-[#efe4d2] px-5 py-12 text-[#3a3026] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-[#806044]/20 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-[#9a6345]"><Coffee className="h-4 w-4" /> Abu’s slow tea ceremony</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Some feelings deserve to steep.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#755e4e]">Four cups for four parts of a story Abu wants Samjhana to drink slowly.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Tea ceremony cups">{cups.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-[#9a6345] bg-white shadow-xl' : 'border-[#806044]/10 bg-white/45 hover:bg-white/80'}`}><span className="flex items-center gap-3"><Leaf className="h-5 w-5 text-[#9a6345]" /><span className="text-xl font-black">{item.label}</span></span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#fff8eb] p-8 shadow-[15px_18px_0_rgba(58,48,38,.12)] sm:p-14"><div className="absolute right-12 top-10 h-24 w-24 rounded-full border border-[#9a6345]/20" /><Sparkles className="h-9 w-9 text-[#9a6345]" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-[#9a6345]">{cup.label}</p><h2 className="mt-5 text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{cup.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#755e4e]">{cup.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-[#806044]/15 pt-6 text-sm font-black text-[#9a6345]"><Heart className="h-4 w-4 fill-current text-rose-400" /> Served gently for my Bhuntu.</div></section></div></div></main>; }
