import React, { useState } from 'react';
import { Heart, Lock, Sparkles } from 'lucide-react';

const promises = [
  { label: 'Promise one', title: 'I will remember the small things.', copy: 'The food, the places, the names, and the details you thought were too ordinary to keep.' },
  { label: 'Promise two', title: 'I will keep making room for your voice.', copy: 'Even across Nepalgunj and Sakai, Abu will keep choosing the conversation that brings us close.' },
  { label: 'Promise three', title: 'I will not rush your softness.', copy: 'You can be playful, quiet, tired, brave, or all four. Abu wants the real Samjhana, not a performance.' },
  { label: 'Promise four', title: 'I will keep walking toward our future.', copy: 'Bardiya, Pokhara, Manang, Mustang, and the light-blue scooter remain plans worth reaching with you.' },
];
export default function SweetPromisesJarPage() { const [selected, setSelected] = useState(0); const promise = promises[selected]; return <main className="min-h-dvh bg-[#f3e7d8] px-5 py-12 text-[#3b2d28] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-[#805b48]/20 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-[#a15d42]"><Lock className="h-4 w-4" /> Abu’s promise cabinet</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Some promises are too important to leave loose.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#765b4d]">Four commitments, written carefully for Samjhana and kept safe inside this birthday world.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Promise cabinet">{promises.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-[#a15d42] bg-white shadow-xl' : 'border-[#805b48]/10 bg-white/45 hover:bg-white/80'}`}><span className="block text-[10px] font-black uppercase tracking-[0.18em] text-[#a15d42]">{item.label}</span><span className="mt-3 block text-xl font-black">{item.title}</span></button>)}</nav><section className="rounded-[2rem] bg-[#fffaf1] p-8 shadow-[15px_18px_0_rgba(59,45,40,.12)] sm:p-14"><Sparkles className="h-9 w-9 text-[#a15d42]" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-[#a15d42]">{promise.label} · sealed by Abu</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{promise.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#765b4d]">{promise.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-[#805b48]/15 pt-6 text-sm font-black text-[#a15d42]"><Heart className="h-4 w-4 fill-current text-rose-400" /> Kept for my Bhuntu.</div></section></div></div></main>; }
