import React, { useState } from 'react';
import { ArrowLeft, Camera, Clapperboard, Play, Volume2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function VideoPage() {
  const navigate = useNavigate();
  const [caption, setCaption] = useState('Samjhana, even a short clip of you makes Abu feel closer to Sakai.');
  const captions = ['Samjhana, even a short clip of you makes Abu feel closer to Sakai.', 'Your smile can cross the Nepalgunj-to-Osaka distance faster than any flight.', 'This is the part Abu would replay when he misses his Sanzu.'];
  const video = '/all_media/tikcdn_beubagah_com_191793ef_79ff_4ac1_9b43_e1f6fc45ccba.mp4';
  return (
    <main className="min-h-dvh bg-[#11100f] text-[#f4eee5]">
      <section className="mx-auto max-w-7xl px-5 py-8 sm:px-10 lg:px-16 lg:py-12">
        <div className="flex items-center justify-between border-b border-white/10 pb-6"><button type="button" onClick={() => navigate('/')} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.22em] text-white/55 transition hover:text-white"><ArrowLeft className="h-4 w-4" /> Abu’s doorway</button><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.22em] text-amber-200/75"><Clapperboard className="h-4 w-4" /> Page six / Samjhana in motion</div></div>
        <div className="grid gap-12 py-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end lg:py-20"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-amber-200/70">A tiny private cinema from Abu</p><h1 className="mt-6 max-w-4xl text-6xl font-black leading-[.88] tracking-[-0.08em] sm:text-8xl">Press play, Sanzu.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/55">Not a gallery. Not a carousel. One moving frame from the world Abu wishes he could step into whenever he misses his Bhuntu.</p></div><div className="lg:pb-2"><p className="text-sm leading-7 text-white/45">Recorded for the girl who can be Samjhana, Sanzu, Bhoot, Bhuntu, Sanu, Babe, or Runchi — and still be the same person Abu cannot stop loving.</p></div></div>
        <div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#201d1a] shadow-[0_25px_100px_rgba(0,0,0,.35)]"><div className="aspect-video bg-black"><video className="h-full w-full object-cover" controls playsInline preload="metadata" src={video}><track kind="captions" /></video></div><div className="grid gap-6 p-6 sm:grid-cols-[1fr_auto] sm:p-8"><div><div className="flex items-center gap-3 text-xs font-bold uppercase tracking-[0.2em] text-amber-200/65"><Camera className="h-4 w-4" /> one memory / Abu’s replay button</div><p className="mt-4 max-w-2xl text-2xl font-bold leading-tight tracking-[-0.03em] text-white">{caption}</p></div><div className="flex items-end gap-2"><button type="button" aria-label="Set first caption" onClick={() => setCaption(captions[0])} className="grid h-10 w-10 place-items-center rounded-full border border-white/15 text-white/65 transition hover:border-amber-200/60 hover:text-amber-100"><Play className="h-4 w-4" /></button><button type="button" aria-label="Set second caption" onClick={() => setCaption(captions[1])} className="grid h-10 w-10 place-items-center rounded-full border border-white/15 text-white/65 transition hover:border-amber-200/60 hover:text-amber-100"><Volume2 className="h-4 w-4" /></button><button type="button" aria-label="Set third caption" onClick={() => setCaption(captions[2])} className="grid h-10 w-10 place-items-center rounded-full border border-white/15 text-white/65 transition hover:border-amber-200/60 hover:text-amber-100"><span className="text-xs font-bold">3</span></button></div></div></div>
        <div className="mt-8 flex flex-wrap justify-between gap-4 border-t border-white/10 pt-5 text-xs font-bold uppercase tracking-[0.18em] text-white/35"><span>Keep the sound if it feels like Samjhana is close.</span><span>Next room: another thing Abu wrote for you.</span></div>
      </section>
    </main>
  );
}
