import React, { useState } from 'react';
import { Coffee, Heart, MessageCircle, Sparkles } from 'lucide-react';

const comforts = [
  { label: 'The first table', title: 'Something warm and familiar', copy: 'A little corner for Chau-Chau, Panipuri, and the comfort of sharing a craving without needing a special occasion.' },
  { label: 'The window seat', title: 'A message from far away', copy: 'A quiet place for the Nepalgunj–Sakai call that makes the room feel less empty and the evening feel more ours.' },
  { label: 'The corner booth', title: 'A nickname on the receipt', copy: 'Sanzu, Bhuntu, Bebo, Sanu, Runchi—names that make an ordinary order feel personally addressed.' },
  { label: 'The table reserved', title: 'For the future morning', copy: 'A seat saved for the light-blue scooter, the mountain roads, and the day Abu is beside you instead of on a screen.' },
];
export default function VirtualCatCafePage() { const [selected, setSelected] = useState(0); const comfort = comforts[selected]; return <main className="min-h-dvh bg-[#f4e8d8] px-5 py-12 text-[#392d27] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-[#835c45]/20 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-[#a36143]"><Coffee className="h-4 w-4" /> Abu’s quiet-corner cafe</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">A table for the comfort you bring with you.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#775e50]">Four corners of a cafe that exists mostly in Abu’s memory, because every good place has Samjhana somewhere in it.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Cafe corners">{comforts.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-[#a36143] bg-white shadow-xl' : 'border-[#835c45]/10 bg-white/45 hover:bg-white/80'}`}><span className="flex items-center gap-3"><MessageCircle className="h-5 w-5 text-[#a36143]" /><span className="text-xl font-black">{item.label}</span></span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#fff9ee] p-8 shadow-[15px_18px_0_rgba(57,45,39,.12)] sm:p-14"><div className="absolute right-10 top-10 h-20 w-20 rounded-full border border-[#a36143]/20" /><Sparkles className="h-9 w-9 text-[#a36143]" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-[#a36143]">{comfort.label}</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{comfort.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#775e50]">{comfort.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-[#835c45]/15 pt-6 text-sm font-black text-[#a36143]"><Heart className="h-4 w-4 fill-current text-rose-400" /> Table reserved by Abu.</div></section></div></div></main>; }
