import React, { useState } from 'react';
import { Flower2, Heart, Sparkles, Wind } from 'lucide-react';

const wishes = [
  { label: 'Wish one', title: 'May today feel completely yours.', copy: 'Not generic, not rushed, and full of the small details that make Samjhana feel seen by Abu.' },
  { label: 'Wish two', title: 'May distance become gentler.', copy: 'May every Nepalgunj–Sakai call leave both of us feeling closer than the map suggests.' },
  { label: 'Wish three', title: 'May the future find us ready.', copy: 'Bardiya, Pokhara, Manang, Mustang, and the light-blue scooter are all better plans with you beside me.' },
  { label: 'Wish four', title: 'May you always know your names are loved.', copy: 'Sanzu, Bhuntu, Bebo, Sanu, Runchi—every nickname is a different way Abu says Samjhana matters.' },
];
export default function WishDandelionPage() { const [selected, setSelected] = useState(0); const wish = wishes[selected]; return <main className="min-h-dvh bg-[#e5f0df] px-5 py-12 text-[#29402d] sm:px-10 sm:py-16"><div className="mx-auto max-w-7xl"><header className="border-b border-emerald-900/15 pb-8"><p className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.28em] text-emerald-700"><Flower2 className="h-4 w-4" /> Abu’s birthday wish garden</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.9] tracking-[-0.08em] sm:text-8xl">Some wishes are really promises in disguise.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#5f7861]">Four seeds of hope for Samjhana, carried gently from Abu’s side of the distance.</p></header><div className="grid gap-10 py-12 lg:grid-cols-[.7fr_1.3fr]"><nav className="space-y-3" aria-label="Birthday wishes">{wishes.map((item, index) => <button key={item.label} type="button" onClick={() => setSelected(index)} className={`w-full rounded-2xl border p-5 text-left transition ${selected === index ? 'border-emerald-700 bg-white shadow-xl' : 'border-emerald-900/10 bg-white/45 hover:bg-white/80'}`}><span className="flex items-center gap-3"><Wind className="h-5 w-5 text-emerald-700" /><span className="text-xl font-black">{item.label}</span></span></button>)}</nav><section className="relative overflow-hidden rounded-[2rem] bg-[#f8fff0] p-8 shadow-[15px_18px_0_rgba(41,64,45,.12)] sm:p-14"><div className="absolute right-12 top-10 h-20 w-20 rounded-full border border-emerald-700/20" /><Sparkles className="h-9 w-9 text-emerald-700" /><p className="mt-12 text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">{wish.label} · carried by Abu</p><h2 className="mt-5 max-w-2xl text-5xl font-black leading-[.94] tracking-[-0.08em] sm:text-7xl">{wish.title}</h2><p className="mt-7 max-w-xl text-xl leading-8 text-[#5f7861]">{wish.copy}</p><div className="mt-10 flex items-center gap-3 border-t border-emerald-900/15 pt-6 text-sm font-black text-emerald-700"><Heart className="h-4 w-4 fill-current text-rose-400" /> For my Bhuntu, with every good wish.</div></section></div></div></main>; }
