import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Heart, Sparkles } from 'lucide-react';
import { ROOM_SEQUENCE } from './RouteGuard';
import { birthdayData } from '../data/birthdayData';

const ROOM_LABELS = [
  '🔐 Secret Door',
  '📸 Memories',
  '🎵 Music',
  '💥 Shatter',
  '🌸 Reasons',
  '💖 Love Quiz',
  '🏺 Compliment Jar',
  '📖 Our Story',
  '✨ Constellations',
  '🎮 Heart Catcher',
  '🎬 Videos',
  '🌏 Distance',
  '🎡 Spin Wheel',
  '✉️ Open When',
  '✈️ Passport & Ticket',
  '💌 Love Letter',
  '🍾 Message in Bottle',
  '🃏 Memory Match',
  '🎶 Music Box',
  '💐 Flowers',
  '🏮 Wish Lanterns',
  '📜 Quotes',
  '📸 Photo Booth',
  '🎟️ Scratch Cards',
  '🌸 Promise Tree',
  '🎁 Mystery Gifts',
  '🗝️ Treasure Chest',
  '🎰 Love Slots',
  '🔮 Horoscope',
  '💓 Love Scanner',
  '🎂 Cake Studio',
  '🐱 Love Pet',
  '🎡 Ferris Wheel',
  '❓ Two Truths',
  '🔤 Word Search',
  '⛲ Wishing Well',
  '🎤 Soundboard',
  '❌ Tic-Tac-Toe',
  '🎆 Heart Fireworks',
  '⏳ Timeline Puzzle',
  '🫧 Bubble Pop',
  '🗺️ Bucket List',
  '📄 Origami Heart',
  '🃏 Affirmations',
  '🎹 Heart Piano',
  '✉️ Wax Sealer',
  '🧩 Love Maze',
  '🥠 Fortune Cookie',
  '🧪 Love Potion',
  '😍 Emoji Story',
  '🧩 Jigsaw Puzzle',
  '🎲 Dare Dice',
  '🎈 Balloon Pop',
  '🎯 Couple Bingo',
  '⭐ Love Review',
  '📔 Couple Diary',
  '🔤 Love Scrabble',
  '🎰 Golden Lottery',
  '🐱 Heart Pet',
  '🔐 Code Vault',
  '🔮 Romantic Tarot',
  '🖼️ Abu & Bhuntu Art Gallery',
  '🫂 Infinite Hugs',
  '🧩 Mini Crossword',
  '📻 Love FM Radio',
  '🕯️ Prayer Candle',
  '🎵 Love Vibe',
  '🔬 Love Science Lab',
  '🪬 Love Bead Bracelet',
  '🍱 Bento Box',
  '🎯 Love Darts Champion',
  '🎟️ Coupon Creator',
  '⭐ Star Certificate',
  '💌 Abu\'s Secret Inbox',
  '🎁 Love Gift Wrapper',
  '💋 Kiss Stamping',
  '🃏 Memory Flip 2',
  '🎧 Sound Wave',
  '✍️ Love Typewriter Studio',
  '💍 Mood Ring',
  '🧩 Heart Tetris',
  '🏹 Cupid Archery',
  '⏰ Love Alarm',
  '🗓️ 365 Date Night Generator',
  '💬 Abu\'s Press Conference',
  '💓 Heartbeat Sync',
  '✉️ Wax Letter',
  '✨ Star Connect',
  '📜 Gratitude Jar',
  '🎐 Wind Chimes',
  '🧩 Picture Slider',
  '🪬 Love Evil Eye',
  '🥗 Love Salad Mixer',
  '🫙 Catch Fireflies',
  '🌵 Love Cactus Garden',
  '🏮 Sky Wishes',
  '🎁 IOU Coupons',
  '💍 Ring Surprise',
  '🎉 Grand Finale',
  '👑 Hall of Fame',
  '⏰ Time Machine',
  '🃏 Memory Match 3',
  '📄 Origami Heart 2',
  '🥠 Fortune Cookie 2',
  '🎫 Scratch Card 2',
  '📡 Audio Waveform',
  '🧠 Sanzu Trivia',
  '📸 Polaroid Booth',
  '👑 Queen Coronation',
  '🗺️ Love Journey Map',
  '🥁 Heartbeat Drum',
  '✈️ Paper Airplanes',
  '🎨 Emoji Art Canvas',
  '🎱 Magic 8-Ball',
  '🔒 Love Lock Bridge',
  '🔐 Secret Cipher',
  '☁️ Cloud Skywriter',
  '🌡️ Love Thermometer',
  '🎬 Movie Ticket Studio',
  '🔮 Snow Globe',
  '🌬️ Wish Dandelion',
  '🎨 Pixel Heart Painter',
  '🎭 Romantic Charades',
  '🏆 Love Trophies',
  '🌹 Rose Garden',
  '📖 Love Mad Libs',
  '🦋 Butterfly Catcher',
  '🎤 Romantic Karaoke',
  '🪞 Magic Mirror Oracle',
  '🌺 Hawaiian Love Lei',
  '✨ Star Drawer',
  '🎡 Wish Wheel',
  '🫧 Bubble Wrap',
  '✨ Scratch Compliments',
  '⚔️ Love vs Loneliness Battle',
  '🐠 Love Aquarium',
  '🧩 Photo Slider',
  '🔐 Coupon Vault',
  '📮 Heart Mailbox',
  '🫧 Love Soap Bubble Maker',
  '💍 Love Ring Donut',
  '📜 Magnet Poetry',
  '🎸 Love Guitar Shredder',
  '⏰ Love Clock',
  '🤳 Love Selfie Sticker Studio',
  '🔮 Love Snow Globe',
  '🎂 Candle Blower',
  '👑 Royal Coronation',
  '🏰 Love Castle Builder',
  '🧭 Heart Compass',
  '🧘 Couple Yoga Challenge',
  '🛸 Love UFO Encounter',
  '📊 Compatibility Matrix',
  '🏠 Dream Home Builder',
  '🎤 Love Open Mic Night',
  '💍 Promise Ring Designer',
  '💖 5 Love Languages',
  '🎪 Love Ring Toss Carnival',
  '🎪 Love Circus Night',
  '📜 Poem Composer',
  '🎂 Bhuntu Birthday Countdown',
  '🧋 Boba Tea Cafe',
  '🏛️ Abu\'s Love Museum',
  '🐱 Kitten Coffee Date',
  '🎞️ Memory Film Reel',
  '👑 Royal Love Archetype',
  '💍 Dream Proposal',
  '📻 Radio 100.4 Bebo FM',
  '🤝 Secret Handshake',
  '🌌 Milky Way Love Trail',
  '🍕 Heart Pizza Bakery',
  '🗝️ Golden Vault Safe',
  '📞 Voicemail Inbox',
  '🦋 Love Metamorphosis',
  '🎟️ Foil Reveal Gallery',
  '🧩 Heart Tangram',
  '✨ Shooting Star Meteors',
  '☕ Matka Chiya Love Date',
  '🎰 Abu & Bhuntu Slot Machine',
  '💓 Heartbeat Tap Challenge',
  '🧁 Macaron Dessert Tower',
  '🧲 Love Magnet Poetry Pro',
  '🌺 Flower Language Decoder',
  '🌊 Love Wave Message',
  '🪶 Weave Dreamcatcher',
  '💬 100 Deep Questions',
  '🍡 Tokyo Street Food Date',
  '⛲ Love Coin Fountain',
  '🍿 Midnight Snack Date',
  '🗝️ Abu\'s Keychain Collection',
  '🌈 Rainbow Promise Bridge',
  '🗺️ Abu & Bhuntu World Map',
  '🪄 Abu\'s Magic Trick',
  '🎈 Hot Air Balloon Love Journey',
  '🎠 Love Amusement Park',
  '🎈 Love Letter Balloons',
  '📖 Photo Scrapbook',
  '👑 Royal Coronation',
  '💬 10,000 I Love You Wall',
  '🎻 Love Violin Serenade',
  '🧶 Love Bracelet Weaver',
  '🏄 Love Surfing Beach',
  '🧋 Boba Tea Love Cafe',
  '🎬 Love Movie Trailer',
  '💃 Love Rhythm Arcade',
  '🌿 Magical Glass Terrarium',
  '🏔️ Mount Everest Love Flag',
  '💎 Diamond Love Safe',
  '💌 3D Pop-Up Love Card',
  '🧩 Love Emoji Rebus',
  '🔐 Abu & Bhuntu Escape Room',
  '🍾 Spin the Bottle',
  '🎯 Trivia Showdown',
  '🎨 Pixel Art Creator',
  '🏹 Abu\'s Arrow Messages',
  '🌅 Love Sunrise Timelapse',
  '💕 First Moments Timeline',
  '🎨 Love Tie-Dye Studio',
  '📚 Couple Yearbook',
  '💌 Love Letter Archive',
  '🎵 Couple Soundtrack',
  '🪄 Love Spell Caster',
  '🧲 Love Magnet Physics',
  '📖 Fairy Tale Generator',
  '🐚 Love Oracle Conch Shell',
  '🐉 Dragon & Princess Adventure',
  '🧙 Love Wizard Tower',
  '🎨 Love Graffiti Spray Wall',
  '💡 Love Neon Sign',
  '😂 Abu & Bhuntu Meme Wall',
  '🌀 Love Kaleidoscope',
  '🏖️ Love Sandcastle Beach',
  '🎄 Love Advent Calendar',
  '🦁 Spirit Animal Love Test',
  '💌 Valentine Card Creator',
  '📅 Dated Calendar',
  '🥠 Fortune Cookie Love',
  '∞ Infinite Reasons Machine',
  '🏆 Love Awards Night',
  '🌸 Four Seasons of Love',
  '🍱 Abu\'s Lunch Bento Box',
  '🎰 Love Casino Night',
  '🌌 Grand Love Universe',
  '📸 Sanzu Masonry Gallery',
  '🥁 Nepali Dhol Beat Studio',
  '🪁 Love Kite Festival',
  '✈️ Nepalgunj to Osaka Flight',
  '🎟️ Romantic Scratch Voucher Book',
  '🎙️ Bhuntu Voice Note Archive',
  '🗺️ Nepal & Japan Milestone Map',
  '🎲 Love Dice of Fate',
  '🌸 Interactive Petal Rain',
  '🪁 Love Kite in the Sky',
  '🧠 Abu\'s Mind Map',
  '🎞️ Vintage 35mm Love Film Strip',
  '🕯️ Virtual Candlelight Dinner',
  '🌌 Orbiting Nicknames Galaxy',
  '🥠 Endless Fortune Cookie Jar',
  '🧳 Dream Vacation Packer',
  '🎐 Wind Chimes Garden',
  '🎠 3D Carousel Photo Slider',
  '🎮 Bhuntu Emoji Whack-A-Heart',
  '🎭 Couple Shadow Theater',
  '✨ Night Sky Neon Writer',
  '🌮 Love Street Food Tour',
  '🍜 Abu\'s Ramen Date',
  '🎬 Abu & Bhuntu Movie Poster',
  '💌 Abu\'s Secret Letter Box',
  '💍 Golden Heart Locket',
  '🎯 Abu\'s Truth or Dare',
  '🎬 Private Cinema Theater',
  '💖 5 Love Languages Quiz',
  '🎭 Bhuntu\'s Alter Egos',
  '🚀 Planet Abu Mission',
  '💌 100 Reasons Why Grid',
  '⌚ Love Watch Designer',
  '🎨 Glowing Heart Doodle Canvas',
  '📻 Love Radio Drama',
  '🎵 Heartbeat Beatmaker Pad',
  '🍀 Lucky Clover Field',
  '🍦 Love Ice Cream Parlor',
  '🏆 Couple Superlative Awards',
  '🧊 Rotating 3D Photo Cube',
  '🎯 Bhuntu Birthday Trivia Wheel',
  '💌 Open When... Collection',
  '🪗 Love Accordion Squeeze',
  '🏠 Our Future Dream Home',
  '💡 Custom Neon Light Designer',
  '🎨 Love Watercolor Studio',
  '🧩 Heart Block Tetris Arcade',
  '💑 Couple Relationship Certificate',
  '🌌 3D Grand Love Galaxy',
  '🎡 Abu & Bhuntu Theme Park',
  '✨ Scratch Reveal Gallery',
  '📖 Love Letter Archive',
  '🪄 Love Spell Caster',
  '🧪 Love Potion Lab',
  '🗺️ Nepal & Japan Milestone Map',
  '👑 THE GRAND 300TH LOVE CORONATION 💖',
];

export default function Navbar() {
  const location = useLocation();
  const navigate = useNavigate();

  const currentPath = location.pathname;
  const seqIndex = ROOM_SEQUENCE.indexOf(currentPath);
  const isSeqPage = seqIndex !== -1;
  const roomLabel = isSeqPage ? ROOM_LABELS[seqIndex] : '🏠 Home';
  const totalRooms = ROOM_SEQUENCE.length;
  const progress = isSeqPage ? (seqIndex + 1) / totalRooms : 0;

  return (
    <>
      <header
        className="fixed top-0 left-0 right-0 z-40 bg-white/95 backdrop-blur-xl shadow-sm border-b border-pink-100"
        style={{ paddingTop: 'env(safe-area-inset-top)' }}
      >
        <div className="max-w-6xl mx-auto px-4 flex items-center justify-between h-14">
          {/* Brand badge - non-navigating static indicator */}
          <div className="flex items-center gap-2 text-left">
            <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-pink-500 to-rose-400 flex items-center justify-center shadow-md flex-shrink-0">
              <Heart className="w-4 h-4 text-white fill-white" />
            </div>
            <div className="leading-tight hidden sm:block">
              <span className="block text-xs font-bold text-gray-900 font-nepali truncate max-w-[120px]">
                {birthdayData.partner.name} & {birthdayData.herName}
              </span>
              <span className="block text-[10px] text-pink-500 font-bold font-ui">
                {birthdayData.anniversaryBadge}
              </span>
            </div>
          </div>

          {/* Current room label & page counter */}
          <div className="flex items-center gap-2 bg-pink-50 px-3 py-1.5 rounded-full border border-pink-200/80 shadow-xs max-w-[220px] sm:max-w-xs">
            <Sparkles className="w-4 h-4 text-rose-500 flex-shrink-0 animate-pulse" />
            <div className="flex flex-col items-start min-w-0">
              <span className="text-xs font-bold text-gray-800 font-ui truncate max-w-[140px] sm:max-w-[180px]">
                {roomLabel}
              </span>
              <span className="text-[11px] text-rose-500 font-ui font-bold">
                {isSeqPage ? `Surprise ${seqIndex + 1} of ${totalRooms} 💕` : 'Birthday Journey 💕'}
              </span>
            </div>
          </div>
        </div>

        {/* Progress bar */}
        <div className="h-1 bg-pink-100">
          <div
            className="h-full bg-gradient-to-r from-pink-400 via-rose-500 to-pink-400 transition-all duration-700 ease-out"
            style={{ width: `${Math.round(progress * 100)}%` }}
          />
        </div>
      </header>

    </>
  );
}
